<?php
require dirname(__DIR__).'/staffing-lifecycle/bootstrap.php';
require_once dirname(__DIR__,2).'/includes/modules/staff-tasks/admin-ui.php';
require_once dirname(__DIR__,2).'/includes/modules/staff-tasks/authority-ui.php';
require_once dirname(__DIR__,2).'/includes/modules/staff-tasks/calendar/ui.php';
$checks=0;$receipts=array();
function cal_check($ok,string $label):void {global $checks;if(!$ok)throw new RuntimeException($label);$checks++;}
function cal_cmd(string $action,int $id,array $input):array {$row=$id?bvmgr_tasks_get_instance($id):null;$r=bvmgr_tasks_command($action,$id,$input,$row['revision']??null,wp_generate_uuid4());cal_check(!is_wp_error($r),'canonical '.$action.(is_wp_error($r)?' '.$r->get_error_code():''));return $r;}
function cal_view(array $args=array()):array {$r=bvmgr_tasks_calendar_read(array_merge(array('date'=>'2030-10-20','view'=>'day'),$args));cal_check(!is_wp_error($r),'calendar read allowed');return $r;}
function cal_has(array $d,int $id,string $bucket='cards'):bool {return $bucket==='cards'?isset($d['cards'][$id]):in_array($id,array_column($d[$bucket],'id'),true);}
function cal_snapshot():array {global $wpdb;$out=array();foreach($wpdb->get_col('SHOW TABLES') as $t){$rows=$wpdb->get_results('SELECT * FROM `'.$t.'`',ARRAY_A);$hashes=array_map(static fn($r)=>hash('sha256',serialize($r)),$rows);sort($hashes);$out[$t]=hash('sha256',serialize($hashes));}return $out;}
update_option('timezone_string','America/Chicago');update_option('start_of_week',1);
bvmgr_staffing_migrate_lifecycle();bvmgr_tasks_install_authority();
$people=array();foreach(array('Avery','Morgan') as $name){$u=wp_insert_user(array('user_login'=>'calendar-'.strtolower($name),'user_pass'=>wp_generate_password(),'role'=>'editor'));$staff=wp_insert_post(array('post_type'=>'vms_staff','post_status'=>'publish','post_title'=>$name));update_post_meta($staff,'_vms_linked_user_id',$u);update_user_meta($u,'_vms_staff_id',$staff);$people[]=$u;}
$venue=wp_insert_post(array('post_type'=>'tribe_venue','post_status'=>'publish','post_title'=>'Calendar test venue'));
$plans=array();foreach(array('Autumn concert','Community market') as $title){$plan=wp_insert_post(array('post_type'=>'vms_event_plan','post_status'=>'publish','post_title'=>$title));foreach(array('_vms_event_date'=>'2030-10-20','_vms_start_time'=>'18:00','_vms_end_time'=>'22:00','_vms_event_plan_status'=>'ready','_vms_venue_id'=>$venue) as $k=>$v)bvmgr_event_occurrence_authorized_write(static fn()=>update_post_meta($plan,$k,$v));$plans[]=$plan;}
$base=array('assignment_mode'=>'person','assignee_user_id'=>$people[0],'event_id'=>$plans[0],'venue_id'=>$venue,'is_required'=>1);
$fixtures=array();
$definitions=array(
 'scheduled'=>array('schedule_source'=>'fixed','start'=>'2030-10-20 10:00','end'=>'2030-10-20 11:30'),
 'deadline'=>array('due_kind'=>'datetime','due_value'=>'2030-10-20 14:15'),
 'date'=>array('due_kind'=>'date','due_value'=>'2030-10-20'),
 'unscheduled'=>array('due_kind'=>'none'),
 'review'=>array('due_kind'=>'date','due_value'=>'2030-10-20'),
 'overdue'=>array('due_kind'=>'datetime','due_value'=>'2000-01-01 15:00'),
 'completed'=>array('due_kind'=>'datetime','due_value'=>'2030-10-20 12:00'),
 'canceled'=>array('schedule_source'=>'fixed','start'=>'2030-10-20 13:00','end'=>'2030-10-20 14:00'),
 'unassigned'=>array('due_kind'=>'date','due_value'=>'2030-10-20'),
 'start'=>array('schedule_source'=>'fixed','start'=>'2030-10-20 16:00'),
 'overnight'=>array('schedule_source'=>'fixed','start'=>'2030-10-19 23:00','end'=>'2030-10-20 01:00'),
 'relative'=>array('schedule_source'=>'event_offset','start_offset'=>-90,'duration_minutes'=>60),
 'other'=>array('due_kind'=>'date','due_value'=>'2030-10-21'),
);
foreach($definitions as $key=>$timing){$input=array_merge($base,array('title'=>'Calendar '.$key,'timing'=>$timing));if($key==='unassigned')$input['assignee_user_id']=0;if($key==='other'){$input['assignee_user_id']=$people[1];$input['event_id']=$plans[1];$input['is_required']=0;}$fixtures[$key]=cal_cmd('create',0,$input);}
cal_cmd('transition',$fixtures['completed']['id'],array('status'=>'done'));cal_cmd('transition',$fixtures['canceled']['id'],array('status'=>'canceled','reason'=>'Synthetic cancellation'));
$wpdb->update(bvmgr_tasks_table_name('task_instances'),array('timing_json'=>null),array('id'=>$fixtures['review']['id']));
$day=cal_view();cal_check(count($day['days'])===1,'day view');$week=cal_view(array('view'=>'week'));cal_check(count($week['days'])===7&&$week['range']['start']->format('Y-m-d')==='2030-10-14','week respects configured first day');
foreach(array('scheduled','deadline','date','completed','canceled','unassigned','start','overnight','relative') as $key)cal_check(cal_has($day,$fixtures[$key]['id']),'day includes '.$key);
foreach(array('unscheduled','review','overdue','unassigned') as $key)cal_check(cal_has($day,$fixtures[$key]['id'],'queue'),'queue includes '.$key);
$placements=$day['days']['2030-10-20'];$by=array();foreach(array_merge($placements['timed'],$placements['all_day']) as $p)$by[$p['task']]=$p;
cal_check($by[$fixtures['scheduled']['id']]['kind']==='scheduled'&&$by[$fixtures['scheduled']['id']]['end']->format('H:i')==='11:30','scheduled real interval');
cal_check($by[$fixtures['deadline']['id']]['kind']==='deadline'&&$by[$fixtures['deadline']['id']]['end']===null&&$by[$fixtures['deadline']['id']]['start']->format('H:i')==='14:15','deadline exact instant without duration');
cal_check($by[$fixtures['date']['id']]['kind']==='date'&&$by[$fixtures['date']['id']]['end']===null,'date is not timed');
cal_check($by[$fixtures['start']['id']]['kind']==='start'&&$by[$fixtures['start']['id']]['end']===null,'start-only has no invented end');
cal_check(!isset($by[$fixtures['review']['id']])&&!isset($by[$fixtures['unscheduled']['id']]),'unplaced tasks have no invented placement');
cal_check($day['cards'][$fixtures['overdue']['id']]['overdue'],'overdue derived');
cal_check($day['cards'][$fixtures['completed']['id']]['status']==='done'&&$day['cards'][$fixtures['canceled']['id']]['status']==='canceled','canonical history statuses');
// Closed work needing review must remain visible when its recorded timing is in range.
$closed_id=$fixtures['canceled']['id'];$closed_row=bvmgr_tasks_get_instance($closed_id);$closed_timing=json_decode($closed_row['timing_json'],true);$closed_timing['review']='synthetic_timing_review';$wpdb->update(bvmgr_tasks_table_name('task_instances'),array('timing_json'=>wp_json_encode($closed_timing)),array('id'=>$closed_id));
$closed_view=cal_view();cal_check(cal_has($closed_view,$closed_id,'queue'),'closed in-range timing review remains visible with all statuses');$wpdb->update(bvmgr_tasks_table_name('task_instances'),array('timing_json'=>$closed_row['timing_json']),array('id'=>$closed_id));
foreach(array(array('assignee'=>$people[0]),array('event'=>$plans[0]),array('venue'=>$venue),array('type'=>'deadline'),array('status'=>'done'),array('required'=>'0'),array('assignee'=>$people[1],'event'=>$plans[1],'type'=>'date','required'=>'0','date'=>'2030-10-21')) as $filters){$d=cal_view($filters);foreach($d['cards'] as $c){if(isset($filters['assignee']))cal_check($c['assignee_id']===$filters['assignee'],'assignee filter');if(isset($filters['event']))cal_check($c['event_id']===$filters['event'],'event filter');if(isset($filters['venue']))cal_check($c['venue_id']===$filters['venue'],'venue filter');if(isset($filters['type']))cal_check($c['type']===$filters['type'],'category/type filter');if(isset($filters['status']))cal_check($c['status']===$filters['status'],'status filter');if(isset($filters['required']))cal_check($c['required']===(bool)$filters['required'],'required/optional filter');}}
cal_check(cal_has($d,$fixtures['other']['id']),'combined filters find matching task');
foreach(array('review','overdue','unassigned') as $focus){$d=cal_view(array('focus'=>$focus));cal_check(count($d['cards'])>0,'shortcut has results '.$focus);foreach($d['cards'] as $c)cal_check(in_array($focus,$c['attention'],true),'shortcut filters '.$focus);}
wp_set_current_user($people[0]);$own=cal_view(array('assignee'=>$people[1]));foreach($own['cards'] as $c)cal_check($c['assignee_id']===$people[0],'self scope overrides forged assignee');$options=bvmgr_tasks_calendar_options($own);cal_check(!isset($options['assignee'][$people[1]],$options['event'][$plans[1]]),'facets cannot leak other staff tasks');
$outsider=wp_insert_user(array('user_login'=>'calendar-denied','user_pass'=>wp_generate_password(),'role'=>'subscriber'));wp_set_current_user($outsider);cal_check(is_wp_error(bvmgr_tasks_calendar_read(array('assignee'=>$people[0]))),'unauthorized server read denied');wp_set_current_user(0);cal_check(is_wp_error(bvmgr_tasks_calendar_read(array())),'anonymous read denied');wp_set_current_user(1);
$r=bvmgr_tasks_calendar_range(bvmgr_tasks_calendar_request(array('view'=>'day','date'=>'2030-03-10')));cal_check($r['end']->getTimestamp()-$r['start']->getTimestamp()===23*3600,'spring DST day uses 23 real hours');
$r=bvmgr_tasks_calendar_range(bvmgr_tasks_calendar_request(array('view'=>'day','date'=>'2030-11-03')));cal_check($r['end']->getTimestamp()-$r['start']->getTimestamp()===25*3600,'fall DST day uses 25 real hours');
$bad=bvmgr_tasks_calendar_request(array('date'=>'2030-02-30','view'=>array(),'assignee'=>array(),'status'=>'open OR 1=1'));cal_check($bad['date']===wp_date('Y-m-d')&&$bad['status']==='all'&&$bad['assignee']===0,'malformed request normalized safely');
$tokyo=cal_cmd('create',0,array_merge($base,array('title'=>'Calendar Tokyo','timing'=>array('timezone'=>'Asia/Tokyo','schedule_source'=>'fixed','start'=>'2030-10-21 01:00','end'=>'2030-10-21 02:00'))));$d=cal_view();cal_check(cal_has($d,$tokyo['id']),'foreign timezone instant maps to site day');
cal_cmd('transition',$fixtures['scheduled']['id'],array('status'=>'done'));$d=cal_view();cal_check($d['cards'][$fixtures['scheduled']['id']]['status']==='done','command completion reflected after reload');cal_cmd('transition',$fixtures['scheduled']['id'],array('status'=>'open'));
$old=bvmgr_tasks_sync_record($fixtures['relative']['id']);bvmgr_event_occurrence_authorized_write(static fn()=>update_post_meta($plans[0],'_vms_event_date','2030-10-22'));clean_post_cache($plans[0]);$pending=cal_view();cal_check($pending['cards'][$fixtures['relative']['id']]['review']==='event_timing_reconciliation_pending','read detects pending dependency without moving task');cal_check(bvmgr_tasks_sync_record($fixtures['relative']['id'])['timing']===$old['timing'],'read did not recalculate canonical timing');bvmgr_tasks_reconcile_event($plans[0]);$moved=cal_view(array('date'=>'2030-10-22'));cal_check(cal_has($moved,$fixtures['relative']['id']),'authoritative reschedule appears on new day');$old_day=cal_view();cal_check(cal_has($old_day,$fixtures['scheduled']['id']),'pinned task stays on old day');
$all=$wpdb->get_results('SELECT * FROM '.bvmgr_tasks_table_name('task_instances').' ORDER BY id',ARRAY_A);$batch=bvmgr_tasks_sync_records($all);foreach($all as $row)cal_check($batch[$row['id']]===bvmgr_tasks_sync_record($row['id']),'single and batch authority contract identical');
// Synthetic Google status only; no credentials or live provider operations.
$task=bvmgr_tasks_sync_record($fixtures['scheduled']['id']);$state=array('version'=>1,'site'=>'calendar-fixture','connections'=>array($people[0]=>array('status'=>'connected','calendar_state'=>'ready')),'mirrors'=>array());$p=bvmgr_google_projection($task,$people[0],$state['site'],true);$m=array('user'=>$people[0],'task'=>$task['task_id'],'state'=>'synced','attempted'=>true,'applied'=>$p['hash']);$state['mirrors'][$people[0].':'.$task['task_id']]=$m;
cal_check(bvmgr_tasks_calendar_sync($state,$task)['state']==='synced','Google synced state');$state['mirrors'][$people[0].':'.$task['task_id']]['state']='failed_retryable';cal_check(bvmgr_tasks_calendar_sync($state,$task)['attention'],'Google failed attention');$state['connections'][$people[0]]['status']='authorization_required';cal_check(bvmgr_tasks_calendar_sync($state,$task)['state']==='authorization_required','Google auth required');cal_check(bvmgr_tasks_calendar_sync(array(),$task)['state']==='not_connected','native calendar needs no Google');
// An unavailable person must surface even when their scheduled work is outside the viewed week.
$future=cal_cmd('create',0,array_merge($base,array('title'=>'Calendar future identity review','assignee_user_id'=>$people[1],'timing'=>array('schedule_source'=>'fixed','start'=>'2035-01-01 10:00','end'=>'2035-01-01 11:00'))));
$staff_id=(int)get_user_meta($people[1],'_vms_staff_id',true);wp_update_post(array('ID'=>$staff_id,'post_status'=>'draft'));$reviewed=cal_view(array('focus'=>'review'));cal_check(cal_has($reviewed,$future['id'],'queue'),'future unavailable assignee remains in attention');wp_update_post(array('ID'=>$staff_id,'post_status'=>'publish'));
$new_venue=wp_insert_post(array('post_type'=>'tribe_venue','post_status'=>'publish','post_title'=>'New canonical venue'));update_post_meta($plans[0],'_vms_venue_id',$new_venue);$venue_view=cal_view(array('venue'=>$new_venue));cal_check(cal_has($venue_view,$fixtures['scheduled']['id'])&&$venue_view['cards'][$fixtures['scheduled']['id']]['venue_id']===$new_venue,'venue filter follows current event context');update_post_meta($plans[0],'_vms_venue_id',$venue);
$recent=cal_cmd('create',0,array_merge($base,array('title'=>'Calendar timezone overdue','timing'=>array('due_kind'=>'datetime','due_value'=>wp_date('Y-m-d H:i:s',time()-3600)))));update_option('timezone_string','Pacific/Honolulu');$changed_zone=cal_view(array('focus'=>'overdue'));cal_check(cal_has($changed_zone,$recent['id'],'queue'),'overdue SQL uses canonical UTC after site timezone changes');update_option('timezone_string','America/Chicago');
// Capture complete table state and reject every attempted mutation/transport during reads/render.
$before=cal_snapshot();$mutations=0;$http=0;$guard=static function($sql)use(&$mutations){if(preg_match('/^\\s*(INSERT|UPDATE|DELETE|REPLACE|ALTER|CREATE|DROP|TRUNCATE)\\b/i',$sql)){$mutations++;throw new RuntimeException('calendar read mutation');}return $sql;};$transport=static function($pre)use(&$http){$http++;throw new RuntimeException('calendar read HTTP');};add_filter('query',$guard,PHP_INT_MAX);add_filter('pre_http_request',$transport,PHP_INT_MAX);
foreach(array('day','week') as $view){$_GET=array('date'=>'2030-10-20','view'=>$view,'page'=>'vms-tasks-calendar');ob_start();bvmgr_tasks_calendar_page();$html=ob_get_clean();cal_check(str_contains($html,'Staff Tasks Calendar')&&str_contains($html,'Details and actions'),'real calendar HTML rendered');cal_check(!str_contains($html,'access_token')&&!str_contains($html,'refresh_token'),'render omits credential fields');file_put_contents(getenv('BVM_CALENDAR_EVIDENCE').'/'.$view.'.html',$html);}
remove_filter('query',$guard,PHP_INT_MAX);remove_filter('pre_http_request',$transport,PHP_INT_MAX);cal_check($mutations===0&&$http===0&&cal_snapshot()===$before,'all tables and zero write/HTTP attempts on reads');
// Many distinct reciprocal staff identities still use two shared validation-link queries.
for($i=0;$i<24;$i++){$uid=wp_insert_user(array('user_login'=>'calendar-volume-person-'.$i,'user_pass'=>wp_generate_password(),'role'=>'editor'));$sid=wp_insert_post(array('post_type'=>'vms_staff','post_status'=>'publish','post_title'=>'Calendar volume staff '.$i));update_post_meta($sid,'_vms_linked_user_id',$uid);update_user_meta($uid,'_vms_staff_id',$sid);cal_cmd('create',0,array_merge($base,array('title'=>'Calendar multi-staff '.$i,'assignee_user_id'=>$uid,'timing'=>array('due_kind'=>'date','due_value'=>'2030-10-20'))));}
$observed=array();$links_observer=static function($sql)use(&$observed){$observed[]=$sql;return $sql;};add_filter('query',$links_observer);$multi=cal_view();remove_filter('query',$links_observer);
$link_queries=array_values(array_filter($observed,static fn($sql)=>str_contains($sql,'SELECT DISTINCT')&&(str_contains($sql,"'_vms_staff_id'")||str_contains($sql,"'_vms_linked_user_id'"))));cal_check(count($link_queries)===2,'multi-staff reciprocal links batched in two queries');
$rows=$wpdb->get_results('SELECT * FROM '.bvmgr_tasks_table_name('task_instances'),ARRAY_A);$projections=bvmgr_tasks_sync_records($rows);foreach($rows as $row)cal_check($projections[$row['id']]===bvmgr_tasks_sync_record($row['id']),'batch identity matches canonical single adapter after multi-staff seed');
// Realistic volume: completed history does not expand the returned task universe.
$sample=bvmgr_tasks_get_instance($fixtures['scheduled']['id']);unset($sample['id']);$sample['status']='done';$sample['generation_key']=null;$sample['timing_json']=wp_json_encode(bvmgr_tasks_timing(array('due_kind'=>'date','due_value'=>'2000-01-01')));$sample['due_at_local']='2000-01-01 23:59:59';
for($i=0;$i<1200;$i++){$sample['title']='Calendar historical '.$i;$wpdb->insert(bvmgr_tasks_table_name('task_instances'),$sample);}
$queries=array();$observe=static function($sql)use(&$queries){$queries[]=$sql;return $sql;};add_filter('query',$observe);$start=microtime(true);$d=cal_view();$elapsed=microtime(true)-$start;remove_filter('query',$observe);cal_check($d['range_scanned']<60&&$d['queue_scanned']<30,'historical volume excluded in SQL');
$sample=bvmgr_tasks_get_instance($fixtures['scheduled']['id']);unset($sample['id']);$sample['generation_key']=null;for($i=0;$i<230;$i++){$sample['title']='Calendar busy day '.$i;$wpdb->insert(bvmgr_tasks_table_name('task_instances'),$sample);}
$queries=array();add_filter('query',$observe);$d=cal_view();remove_filter('query',$observe);cal_check($d['range_more']&&$d['range_scanned']===200,'range cap explicitly reports partial view');$second=cal_view(array('range_page'=>1));cal_check(count($second['cards'])>0&&!$second['range_more'],'next range page reaches remaining work');
$single_reads=count(array_filter($queries,static fn($s)=>str_contains($s,'vms_task_instances')&&preg_match('/WHERE id = [0-9]/',$s)));cal_check($single_reads===0,'batch calendar has no per-task record lookups');cal_check(count($queries)<90,'bounded queries at 200 visible tasks');
$receipts=array('assertions'=>$checks,'table_count'=>count($before),'read_mutations'=>$mutations,'read_http'=>$http,'history_fixture_count'=>1200,'visible_query_count'=>count($queries),'range_limit'=>200,'attention_limit'=>100,'history_read_seconds'=>$elapsed);
file_put_contents(getenv('BVM_CALENDAR_EVIDENCE').'/integration-result.json',wp_json_encode($receipts,JSON_PRETTY_PRINT));echo 'PASS '.$checks.' native Staff Tasks calendar assertions'.PHP_EOL;echo wp_json_encode($receipts).PHP_EOL;
