<?php
require dirname(__DIR__).'/staffing-lifecycle/bootstrap.php';
require_once dirname(__DIR__,2).'/includes/modules/staff-tasks/admin-ui.php';
require_once dirname(__DIR__,2).'/includes/modules/staff-tasks/authority-ui.php';
$checks=0; $mail=array(); $transport=true;
function task_check($ok,string $label): void { global $checks; if (!$ok) throw new RuntimeException($label); $checks++; }
function task_command(string $action,int $id,array $input,array $options=array()) { $row=$id?bvmgr_tasks_get_instance($id):null; return bvmgr_tasks_command($action,$id,$input,$options['revision']??($row['revision']??null),$options['operation']??wp_generate_uuid4()); }
function task_ok($result,string $label): array { task_check(!is_wp_error($result),$label.(is_wp_error($result)?': '.$result->get_error_message():'')); return $result; }
function task_logs(): int { global $wpdb; return (int)$wpdb->get_var('SELECT COUNT(*) FROM '.bvmgr_tasks_table_name('task_logs')); }
update_option('timezone_string','America/Chicago');
task_check(!empty(bvmgr_staffing_migrate_lifecycle()['ok']),'accepted staffing schema installed');
bvmgr_tasks_install_authority(); task_check(bvmgr_tasks_authority_ready(),'explicit schema ready'); $logs=task_logs(); bvmgr_tasks_install_authority(); task_check(task_logs()===$logs,'idempotent installation');
add_filter('pre_wp_mail',static function($pre,$m)use(&$mail,&$transport){
 task_check(empty($GLOBALS['bvmgr_tasks_transaction'])&&!bvmgr_staffing_transaction_active(),'transport after commit');
 $reader=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST); $reader->set_prefix($GLOBALS['wpdb']->prefix); $last=$reader->get_row("SELECT * FROM {$reader->prefix}vms_notify_log WHERE source='vms_staff_tasks' ORDER BY id DESC LIMIT 1",ARRAY_A);
 $work=json_decode($last['payload_json']??'',true); task_check(($work['phase']??'')==='attempt','independently visible durable attempt');
 foreach ($work['tasks'] as $t) task_check((int)$reader->get_var($reader->prepare("SELECT revision FROM {$reader->prefix}vms_task_instances WHERE id=%d",$t['id']))===$t['revision'],'independent committed task revision');
 $reader->close(); $mail[]=$m; if ($transport==='throw') throw new RuntimeException('unknown transport'); return $transport;
},PHP_INT_MAX,2);
$users=array();$staff=array(); foreach(array('a','b') as $k){$users[$k]=wp_insert_user(array('user_login'=>'task-'.$k,'user_pass'=>wp_generate_password(),'user_email'=>'task-'.$k.'@example.invalid','role'=>'editor'));task_check(!is_wp_error($users[$k]),'user seeded');$staff[$k]=wp_insert_post(array('post_type'=>'vms_staff','post_status'=>'publish','post_title'=>'Task staff '.$k));update_post_meta($staff[$k],'_vms_linked_user_id',$users[$k]);update_user_meta($users[$k],'_vms_staff_id',$staff[$k]);}
$manual=array('title'=>'Order ice','assignment_mode'=>'person','assignee_user_id'=>$users['a'],'timing'=>array('due_kind'=>'date','due_value'=>'2030-10-18'));
$op=wp_generate_uuid4();$a=task_ok(task_command('create',0,$manual,array('operation'=>$op)),'manual creation');task_check($a['revision']==1,'first revision');task_check(count($mail)===1,'initial assignment once');$n=task_logs();$again=task_ok(task_command('create',0,$manual,array('operation'=>$op)),'create replay');task_check($again['id']===$a['id']&&task_logs()===$n&&count($mail)===1,'stable replay task/audit/mail');
$record=bvmgr_tasks_sync_record((int)$a['id']);task_check($record['timing']['due_kind']==='date'&&!$record['scheduled'],'date only not timeblock');
$before=$a;$op=wp_generate_uuid4();$a=task_ok(task_command('transition',$a['id'],array('status'=>'done'),array('operation'=>$op)),'complete');$n=task_logs();task_ok(bvmgr_tasks_command('transition',$a['id'],array('status'=>'done'),(int)$before['revision'],$op),'complete replay');task_check(task_logs()===$n,'duplicate completion audit-free');task_check($a['completed_by_user_id']==1&&!empty($a['completed_at_local']),'completion attribution');
$a=task_ok(task_command('transition',$a['id'],array('status'=>'open')),'reopen');task_check((int)$a['id']===$record['task_id']&&task_logs()===$n+1,'same identity with retained completion history');
$old_revision=(int)$a['revision'];$a=task_ok(task_command('assignment',$a['id'],array('assignee_user_id'=>$users['b'],'assignment_mode'=>'person','assignment_locked'=>true)),'reassign');task_check(is_wp_error(bvmgr_tasks_command('transition',$a['id'],array('status'=>'done'),$old_revision,wp_generate_uuid4())),'stale complete vs reassignment');
wp_set_current_user($users['a']);task_check(is_wp_error(task_command('transition',$a['id'],array('status'=>'done'))),'former assignee denied');wp_set_current_user($users['b']);$a=task_ok(task_command('transition',$a['id'],array('status'=>'done')),'self completion');task_check(is_wp_error(task_command('transition',$a['id'],array('status'=>'open'))),'self reopen denied');wp_set_current_user(1);$a=task_ok(task_command('transition',$a['id'],array('status'=>'open')),'manager reopen');
$plan=wp_insert_post(array('post_type'=>'vms_event_plan','post_status'=>'publish','post_title'=>'Task event'));
foreach(array('_vms_event_date'=>'2030-10-20','_vms_start_time'=>'20:00','_vms_end_time'=>'23:00','_vms_event_plan_status'=>'ready','_vms_event_plan_start_datetime'=>'1990-01-01 00:00:00') as $k=>$v)bvmgr_event_occurrence_authorized_write(static fn()=>update_post_meta($plan,$k,$v));
$event=bvmgr_tasks_get_event_context($plan);if(!$event)echo json_encode(array('plan'=>$plan,'post'=>get_post_status($plan),'meta'=>get_post_meta($plan),'occurrence'=>bvmgr_event_occurrence_for_plan($plan),'timezone'=>wp_timezone_string()),JSON_PRETTY_PRINT); task_check($event['event_start_local']==='2030-10-20 20:00:00','canonical occurrence overrides stale derived datetime');task_check($event['calendar_warning']!=='','stale TEC diagnostic');
$timing=array('due_kind'=>'datetime','due_source'=>'event_offset','due_offset'=>-60,'schedule_source'=>'event_offset','start_offset'=>-120,'duration_minutes'=>90);
$template=bvmgr_tasks_upsert_task_template(array('title'=>'Open gates','is_active'=>1,'scope'=>'event','assignment_mode'=>'person','assignee_user_id'=>$users['a'],'due_mode'=>'event_offset','due_offset_minutes'=>-60,'timing'=>$timing));task_check(!is_wp_error($template),'template creation');
$checklist=bvmgr_tasks_upsert_checklist_template(array('name'=>'Event task checklist','is_active'=>1,'scope'=>'event','apply_mode'=>'default_all_events'));task_check(!is_wp_error($checklist),'checklist creation');task_check(!is_wp_error(bvmgr_tasks_replace_checklist_items($checklist,array(array('task_template_id'=>$template)))),'checklist link');
$generated=bvmgr_tasks_generate_for_event($plan);task_check(!is_wp_error($generated)&&$generated['instances_created']===1,'template generation');$rows=bvmgr_tasks_get_instances_for_event($plan);$g=$rows[0];$projection=bvmgr_tasks_sync_record($g['id']);task_check($projection['timing']['due_value']==='2030-10-20 19:00:00'&&$projection['timing']['start']==='2030-10-20 18:00:00'&&$projection['timing']['end']==='2030-10-20 19:30:00','relative due and scheduled distinction');
$n=task_logs();bvmgr_tasks_generate_for_event($plan);task_check(count(bvmgr_tasks_get_instances_for_event($plan))===1&&task_logs()===$n,'repeated generator idempotent');
$g=task_ok(task_command('transition',$g['id'],array('status'=>'done')),'complete generated');bvmgr_tasks_generate_for_event($plan);task_check(count(bvmgr_tasks_get_instances_for_event($plan))===1,'completed template never recreated');
$t=bvmgr_tasks_get_task_template($template);$t['title']='Changed future gates';$t['due_offset_minutes']=-30;bvmgr_tasks_upsert_task_template($t,$template);bvmgr_tasks_generate_for_event($plan);task_check(bvmgr_tasks_get_instance($g['id'])['title']==='Open gates','template edit preserves completed instance');
$g=task_ok(task_command('transition',$g['id'],array('status'=>'open')),'reopen generated');
$pinned=task_ok(task_command('create',0,array('title'=>'Pinned setup','event_id'=>$plan,'timing'=>array('schedule_source'=>'fixed','start'=>'2030-10-20 15:00','end'=>'2030-10-20 16:30'))),'pinned creation');
// This test updates canonical fixture input explicitly; real occurrence command is exercised in browser acceptance.
bvmgr_event_occurrence_authorized_write(static function()use($plan){update_post_meta($plan,'_vms_event_date','2030-10-21');});clean_post_cache($plan);$n=task_logs();$reconciled=bvmgr_tasks_reconcile_event($plan);task_check(empty($reconciled['error']),'event reconcile');task_check(bvmgr_tasks_sync_record($g['id'])['timing']['start']==='2030-10-21 18:00:00','relative instance follows new occurrence');task_check(bvmgr_tasks_sync_record($pinned['id'])['timing']['start']==='2030-10-20 15:00:00','pinned schedule preserved');bvmgr_tasks_reconcile_event($plan);task_check(task_logs()===$n+1,'repeat reschedule no audit');
update_post_meta($plan,'_vms_event_plan_status','cancelled');bvmgr_tasks_reconcile_event($plan);task_check(bvmgr_tasks_sync_record($g['id'])['review']==='event_cancelled'&&bvmgr_tasks_get_instance($g['id'])['status']==='open','default cancellation review retains task');
$count=count(bvmgr_tasks_get_instances_for_event($plan));bvmgr_tasks_generate_for_event($plan);task_check(count(bvmgr_tasks_get_instances_for_event($plan))===$count,'canceled event no generation');
$cancel=task_ok(task_command('create',0,array('title'=>'Cancel policy','event_id'=>$plan,'timing'=>array('cancellation_policy'=>'cancel'))),'cancel policy seed');bvmgr_tasks_reconcile_event($plan);task_check(bvmgr_tasks_get_instance($cancel['id'])['status']==='canceled','explicit cancellation policy');
$unassigned=task_ok(task_command('create',0,array('title'=>'Unassigned')),'unassigned valid');task_check(empty($unassigned['assignee_user_id']),'unassigned distinct valid state');task_check(is_wp_error(task_command('assignment',$unassigned['id'],array('assignment_mode'=>'person','assignee_user_id'=>999999))),'missing assignee rejected');
wp_update_post(array('ID'=>$staff['a'],'post_status'=>'draft'));task_check(is_wp_error(task_command('assignment',$unassigned['id'],array('assignment_mode'=>'person','assignee_user_id'=>$users['a']))),'inactive staff rejected');wp_update_post(array('ID'=>$staff['a'],'post_status'=>'publish'));
$dup=wp_insert_user(array('user_login'=>'task-duplicate','user_pass'=>'fixture','role'=>'editor'));update_user_meta($dup,'_vms_staff_id',$staff['a']);task_check(!bvmgr_tasks_person_valid($users['a']),'duplicate identity rejected');delete_user_meta($dup,'_vms_staff_id');
foreach(array('2030-03-10 02:30:00','2030-11-03 01:30:00') as $clock){try{bvmgr_tasks_parse_clock($clock,'America/Chicago');$failed=false;}catch(Throwable $e){$failed=true;}task_check($failed,'DST gap/fold fail closed');}
$tokyo=bvmgr_tasks_timing(array('timezone'=>'Asia/Tokyo','due_kind'=>'datetime','due_value'=>'2030-10-20 10:00'));task_check($tokyo['due_utc']==='2030-10-20 01:00:00','per-task timezone not hardcoded');task_check(bvmgr_tasks_recurrence_next_due_local('2030-01-31 10:00:00','monthly')==='2030-02-28 10:00:00','month-end clamp');
$rec=task_ok(task_command('create',0,array('title'=>'Monthly recurring','due_at_local'=>'2030-01-31 10:00:00','recurrence_pattern'=>'monthly')),'recurrence seed');$rec=task_ok(task_command('transition',$rec['id'],array('status'=>'done')),'recurrence completion');$next=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM %i WHERE generation_key=%s',bvmgr_tasks_table_name('task_instances'),'recurrence:'.$rec['id']));task_check($next>0,'durable successor identity');task_ok(task_command('transition',$rec['id'],array('status'=>'open')),'reopen recurrence parent');task_ok(task_command('transition',$rec['id'],array('status'=>'done')),'recomplete parent');task_check((int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE generation_key=%s',bvmgr_tasks_table_name('task_instances'),'recurrence:'.$rec['id']))===1,'successor not duplicated');task_ok(task_command('transition',$next,array('status'=>'canceled','reason'=>'End occurrence chain')),'cancel successor');task_check(!(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE generation_key=%s',bvmgr_tasks_table_name('task_instances'),'recurrence:'.$next)),'cancel stops recurrence progression');
$n=task_logs();$m=count($mail);ob_start();bvmgr_tasks_timing_summary($a);ob_end_clean();bvmgr_tasks_sync_record($a['id']);bvmgr_tasks_get_instances(array());task_check(task_logs()===$n&&count($mail)===$m,'pure projection/list reads');
$transport=false;$f=task_ok(task_command('create',0,array('title'=>'Transport failure','assignee_user_id'=>$users['b'])),'transport failure leaves task committed');$latest=$wpdb->get_row("SELECT * FROM {$wpdb->prefix}vms_notify_log WHERE source='vms_staff_tasks' ORDER BY id DESC LIMIT 1",ARRAY_A);task_check($latest['status']==='failed','transport failure recorded');$n=count($mail);bvmgr_tasks_delivery_tick();task_check(count($mail)===$n,'safe retry cooldown');$wpdb->update(bvmgr_notify_log_table_name(),array('created_at'=>gmdate('Y-m-d H:i:s',time()-65)),array('id'=>$latest['id']));$transport=true;bvmgr_tasks_delivery_tick();task_check(count($mail)===$n+1&&bvmgr_tasks_delivery_latest($latest['event_key'])['status']==='sent','same identity retry succeeds');bvmgr_tasks_delivery_tick();task_check(count($mail)===$n+1,'successful retry dedupe');
echo "PASS $checks Staff Tasks authority assertions; ".count($mail)." intercepted mail attempts\n";
