<?php
require __DIR__.'/authority.php';
function task_race(array $jobs): array {
 $dir=sys_get_temp_dir().'/bvm-task-race-'.wp_generate_uuid4();mkdir($dir,0700);$procs=$pipes=$out=array();
 try {
  foreach($jobs as $i=>$job){$job+=array('ready'=>$dir.'/ready'.$i,'go'=>$dir.'/go','mail'=>$dir.'/mail');file_put_contents($dir.'/job'.$i,json_encode($job));$procs[$i]=proc_open(array(PHP_BINARY,__DIR__.'/worker.php',$dir.'/job'.$i),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')),$pipes[$i]);fclose($pipes[$i][0]);}
  $deadline=microtime(true)+15;do{$ready=true;foreach($jobs as $i=>$job)$ready=$ready&&is_file($dir.'/ready'.$i);if(!$ready)usleep(10000);}while(!$ready&&microtime(true)<$deadline);task_check($ready,'independent task workers ready');file_put_contents($dir.'/go','go');
  foreach($procs as $i=>$proc){$stdout=stream_get_contents($pipes[$i][1]);$stderr=stream_get_contents($pipes[$i][2]);fclose($pipes[$i][1]);fclose($pipes[$i][2]);$exit=proc_close($proc);$procs[$i]=null;task_check($exit===0||(!empty($jobs[$i]['crash_before_audit'])&&$exit===25)||(!empty($jobs[$i]['crash_mail'])&&$exit===23),'worker result '.$stderr.$stdout);$out[]=json_decode($stdout,true);}
  return array($out,is_file($dir.'/mail')?count(file($dir.'/mail')):0);
 }finally{foreach($procs as $proc)if(is_resource($proc)){proc_terminate($proc);proc_close($proc);}foreach(glob($dir.'/*') as $p)unlink($p);rmdir($dir);}
}
function task_job(array $row,string $action,array $input,string $op=''): array {return array('kind'=>'command','id'=>(int)$row['id'],'action'=>$action,'input'=>$input,'revision'=>(int)$row['revision'],'operation'=>$op?:wp_generate_uuid4());}
$race=task_ok(task_command('create',0,array('title'=>'Race task')),'race fixture');$n=task_logs();$job=task_job($race,'transition',array('status'=>'done'));
[$out,$sent]=task_race(array($job,$job));task_check($out[0]['ok']&&$out[1]['ok']&&task_logs()===$n+1,'same complete operation one audit');
foreach(array(array('transition',array('status'=>'done'),'assignment',array('assignment_mode'=>'person','assignee_user_id'=>$users['a'])),array('transition',array('status'=>'done'),'transition',array('status'=>'canceled','reason'=>'competing cancel')),array('assignment',array('assignment_mode'=>'person','assignee_user_id'=>$users['a']),'assignment',array('assignment_mode'=>'person','assignee_user_id'=>$users['b']))) as $pair){
 $race=task_ok(task_command('create',0,array('title'=>'Competing mutations')),'race seed');$n=task_logs();[$out,$sent]=task_race(array(task_job($race,$pair[0],$pair[1]),task_job($race,$pair[2],$pair[3])));task_check(count(array_filter($out,static fn($r)=>$r['ok']))===1,'one competing revision wins');task_check(task_logs()===$n+1&&bvmgr_tasks_get_instance($race['id'])['revision']==2,'one coherent audit/revision');task_check(in_array('stale_task',array_column($out,'error'),true),'loser gets stale result');
}
update_post_meta($plan,'_vms_event_plan_status','ready');$template2=bvmgr_tasks_upsert_task_template(array('title'=>'Concurrent generation','is_active'=>1,'scope'=>'event','assignment_mode'=>'person','due_mode'=>'none','due_offset_minutes'=>''));$items=bvmgr_tasks_get_checklist_items($checklist);$items[]=array('task_template_id'=>$template2);bvmgr_tasks_replace_checklist_items($checklist,$items);$n=count(bvmgr_tasks_get_instances_for_event($plan));[$out,$sent]=task_race(array(array('kind'=>'generate','plan'=>$plan),array('kind'=>'generate','plan'=>$plan)));task_check($out[0]['ok']&&$out[1]['ok']&&count(bvmgr_tasks_get_instances_for_event($plan))===$n+1,'concurrent template generation one instance');
bvmgr_event_occurrence_authorized_write(static fn()=>update_post_meta($plan,'_vms_event_date','2030-10-22'));clean_post_cache($plan);
$row=bvmgr_tasks_get_instance($g['id']);task_check(bvmgr_tasks_sync_record($g['id'])['review']==='event_timing_reconciliation_pending','stale relative projection flags review without repair');
$job=task_job($row,'timing',array('due_kind'=>'none','schedule_source'=>'fixed','start'=>'2030-12-01 10:00','end'=>'2030-12-01 11:00'));[$out,$sent]=task_race(array($job,array('kind'=>'reconcile','plan'=>$plan)));
if (!$out[0]['ok']) {task_check($out[0]['error']==='stale_task','manual edit conflict explicit');task_ok(task_command('timing',$g['id'],$job['input']),'review then retry pin');}
$final=bvmgr_tasks_sync_record($g['id']);task_check($final['timing']['schedule_source']==='fixed'&&$final['timing']['start']==='2030-12-01 10:00:00','manual pin survives competing actual reschedule');
// Real row and audit failures must roll back together; same request can retry.
$op=wp_generate_uuid4();$input=array('title'=>'Rollback before audit');$count=(int)$wpdb->get_var('SELECT COUNT(*) FROM '.bvmgr_tasks_table_name('task_instances'));$n=task_logs();$fail=static function($sql){return str_starts_with($sql,'INSERT INTO `'.bvmgr_tasks_table_name('task_logs').'`')?'INVALID TASK AUDIT SQL':$sql;};add_filter('query',$fail,PHP_INT_MAX);$r=bvmgr_tasks_command('create',0,$input,null,$op);remove_filter('query',$fail,PHP_INT_MAX);task_check(is_wp_error($r)&&task_logs()===$n&&(int)$wpdb->get_var('SELECT COUNT(*) FROM '.bvmgr_tasks_table_name('task_instances'))===$count,'audit failure rolls back task');task_ok(bvmgr_tasks_command('create',0,$input,null,$op),'retry after audit rollback');
$op=wp_generate_uuid4();$job=array('kind'=>'command','action'=>'create','id'=>0,'input'=>array('title'=>'Crash before commit'),'operation'=>$op,'crash_before_audit'=>true);[$out,$sent]=task_race(array($job));task_check(!(int)$wpdb->get_var($wpdb->prepare('SELECT COUNT(*) FROM %i WHERE generation_key=%s',bvmgr_tasks_table_name('task_instances'),'manual:'.$op)),'process interruption leaves no uncommitted task');task_ok(bvmgr_tasks_command('create',0,$job['input'],null,$op),'restart same create identity');
// Pending audit recovers after queue persistence failure, with two workers racing.
$queue_fail=static fn($sql)=>str_starts_with($sql,'INSERT INTO `'.bvmgr_notify_log_table_name().'`')?'INVALID TASK QUEUE SQL':$sql;add_filter('query',$queue_fail,PHP_INT_MAX);$recover=task_ok(task_command('create',0,array('title'=>'Queue recovery','assignee_user_id'=>$users['b'])),'queue failure leaves authoritative task');remove_filter('query',$queue_fail,PHP_INT_MAX);[$out,$sent]=task_race(array(array('kind'=>'tick'),array('kind'=>'tick')));task_check($sent===1,'concurrent queue recovery one mail');
$job=array('kind'=>'command','action'=>'create','id'=>0,'input'=>array('title'=>'Transport crash','assignee_user_id'=>$users['b']),'operation'=>wp_generate_uuid4(),'crash_mail'=>true);[$out,$sent]=task_race(array($job));task_check($sent===1,'crashed worker reached transport once');[$out,$sent]=task_race(array(array('kind'=>'tick'),array('kind'=>'tick')));task_check($sent===0,'restart never repeats uncertain attempt');
// Confirmed canonical role authority resolves and clears as staffing changes.
$term=wp_insert_term('Task race role','vms_staff_role');$role=(int)$term['term_id'];wp_set_post_terms($staff['a'],array($role),'vms_staff_role');$now=bvmgr_staffing_now_mysql_utc();$wpdb->insert(bvmgr_staffing_table_name('event_slots'),array('event_plan_id'=>$plan,'role_id'=>$role,'headcount_needed'=>1,'shift_time_mode'=>'absolute','shift_start_local'=>'18:00','shift_end_local'=>'23:00','status'=>'active','created_at'=>$now,'updated_at'=>$now));$slot=(int)$wpdb->insert_id;
$r=bvmgr_staffing_atomic(static function()use($slot,$staff){bvmgr_staffing_matrix_proposals($slot,array($staff['a']));bvmgr_staffing_sync_lifecycle_window($slot);return array('ok'=>true);});task_check($r['ok'],'staffing proposal');$slug=get_term($role)->slug;$role_task=task_ok(task_command('create',0,array('title'=>'Confirmed role task','event_id'=>$plan,'assignment_mode'=>'scheduled_role','role_key'=>$slug)),'role task');task_check(empty($role_task['assignee_user_id']),'proposed staffing not committed responsibility');$assignment=(int)$wpdb->get_var($wpdb->prepare('SELECT assignment_id FROM %i WHERE slot_id=%d',bvmgr_staffing_table_name('assignments'),$slot));$a_row=bvmgr_staffing_lifecycle_row($assignment);$r=bvmgr_staffing_transition_assignment($assignment,'confirmed',array('context'=>'operator','event_plan_id'=>$plan,'revision'=>$a_row['revision'],'operation_id'=>wp_generate_uuid4(),'reason'=>'test'));task_check($r['ok']&&(int)bvmgr_tasks_get_instance($role_task['id'])['assignee_user_id']===$users['a'],'confirmed staffing automatically resolves task');$a_row=bvmgr_staffing_lifecycle_row($assignment);$r=bvmgr_staffing_transition_assignment($assignment,'canceled',array('context'=>'operator','event_plan_id'=>$plan,'revision'=>$a_row['revision'],'operation_id'=>wp_generate_uuid4(),'reason'=>'test'));task_check($r['ok']&&empty(bvmgr_tasks_get_instance($role_task['id'])['assignee_user_id']),'canceled staffing clears unlocked task');
// Reminder hook repair and replay, using new due tasks only.
$settings=bvmgr_tasks_get_settings();$settings['notify_due_soon_alerts']=1;$settings['notify_overdue_alerts']=1;bvmgr_tasks_update_settings($settings);$due=wp_date('Y-m-d H:i:s',time()+1800);$remind=task_ok(task_command('create',0,array('title'=>'Due reminder','assignee_user_id'=>$users['b'],'due_at_local'=>$due)),'reminder seed');$n=count($mail);do_action('vms_tasks_notifications_tick');task_check(count($mail)>$n,'scheduled hook reaches reminder callback');$n=count($mail);do_action('vms_tasks_notifications_tick');task_check(count($mail)===$n,'duplicate reminder cron does not resend');
require __DIR__.'/edge-cases.php';
echo "PASS $checks Staff Tasks authority/concurrency/recovery assertions; ".count($mail)." main-process intercepted attempts\n";
