<?php
// Calendar recurrence retains the root month-day and the task's own local clock.
$monthly=task_ok(task_command('create',0,array('title'=>'Month anchor','recurrence_pattern'=>'monthly','timing'=>array('timezone'=>'Asia/Tokyo','due_kind'=>'date','due_value'=>'2030-01-31'))),'monthly date seed');
foreach(array('2030-02-28','2030-03-31') as $expected){task_ok(task_command('transition',$monthly['id'],array('status'=>'done')),'monthly advance');$monthly=$wpdb->get_row($wpdb->prepare('SELECT * FROM %i WHERE generation_key=%s',bvmgr_tasks_table_name('task_instances'),'recurrence:'.$monthly['id']),ARRAY_A);task_check(bvmgr_tasks_sync_record($monthly['id'])['timing']['due_value']===$expected,'root month-day survives short month');}
$daily=task_ok(task_command('create',0,array('title'=>'DST wall clocks','recurrence_pattern'=>'daily','timing'=>array('timezone'=>'America/Chicago','due_kind'=>'datetime','due_value'=>'2030-03-09 10:00','schedule_source'=>'fixed','start'=>'2030-03-09 08:00','end'=>'2030-03-09 09:00'))),'DST daily seed');task_ok(task_command('transition',$daily['id'],array('status'=>'done')),'daily completion across DST');$successor=(int)$wpdb->get_var($wpdb->prepare('SELECT id FROM %i WHERE generation_key=%s',bvmgr_tasks_table_name('task_instances'),'recurrence:'.$daily['id']));$d=bvmgr_tasks_sync_record($successor);task_check($d['timing']['due_value']==='2030-03-10 10:00:00'&&$d['timing']['start']==='2030-03-10 08:00:00','local recurrence clocks stable across DST');
$n=task_logs();$items=bvmgr_tasks_get_checklist_items($checklist);bvmgr_tasks_replace_checklist_items($checklist,$items);task_check(task_logs()===$n,'identical checklist definition no audit');
$t=bvmgr_tasks_get_task_template($template);$prior=json_decode($t['timing_json'],true);bvmgr_tasks_upsert_task_template($t,$template);task_check(task_logs()===$n,'identical template no audit');task_check(json_decode(bvmgr_tasks_get_task_template($template)['timing_json'],true)['schedule_source']===$prior['schedule_source'],'ordinary template edit retains schedule policy');
// An operation fingerprint cannot be reused to change different content.
$op=wp_generate_uuid4();$t=task_ok(task_command('create',0,array('title'=>'Fingerprint'),array('operation'=>$op)),'fingerprint seed');task_check(is_wp_error(task_command('create',0,array('title'=>'Different content'),array('operation'=>$op))),'reused UUID content mismatch rejected');
$n=task_logs();$guard=bvmgr_tasks_atomic(static function(){global $wpdb;$wpdb->query('CREATE TABLE bvm_illegal_task_table (id INT)');return true;});task_check(is_wp_error($guard)&&task_logs()===$n,'DDL refused in task transaction');
$guard=bvmgr_tasks_atomic(static function(){global $wpdb;$wpdb->query("UPDATE {$wpdb->options} SET option_value='illegal' WHERE option_name='blogname'");return true;});task_check(is_wp_error($guard),'non-task write refused');
// Actual digest hook and replay use the existing task notification template.
$settings=bvmgr_tasks_get_settings();$settings['notify_daily_digest']=1;$settings['notify_digest_time']='00:00';bvmgr_tasks_update_settings($settings);$n=count($mail);do_action('vms_tasks_notifications_digest_tick');task_check(count($mail)>$n,'actual digest hook sends existing template');$n=count($mail);do_action('vms_tasks_notifications_digest_tick');task_check(count($mail)===$n,'daily digest replay dedupes');
// Full disposable database read containment, including render/filter/history projection.
function task_manifest(): array {global $wpdb;$m=array();foreach($wpdb->get_col('SHOW TABLES') as $table){$rows=$wpdb->get_results($wpdb->prepare('SELECT * FROM %i',$table),ARRAY_A);$hashes=array_map(static fn($r)=>hash('sha256',serialize($r)),$rows);sort($hashes);$m[$table]=hash('sha256',serialize($hashes));}return $m;}
$before=task_manifest();$attempts=array();$guard=static function($sql)use(&$attempts){if(preg_match('/^\s*(INSERT|UPDATE|DELETE|REPLACE|CREATE|ALTER|DROP|TRUNCATE)\b/i',$sql)){$attempts[]=$sql;throw new RuntimeException('read attempted write');}return $sql;};add_filter('query',$guard,PHP_INT_MAX);$n=count($mail);
for($i=0;$i<3;$i++){bvmgr_tasks_get_instances(array('status'=>'open','search'=>'task'));bvmgr_tasks_get_instances_for_event($plan);foreach(bvmgr_tasks_get_instances_for_event($plan) as $row){bvmgr_tasks_sync_record($row['id']);ob_start();bvmgr_tasks_timing_summary($row);ob_end_clean();}$_GET['task_id']=$a['id'];ob_start();bvmgr_tasks_detail_page();ob_end_clean();}
remove_filter('query',$guard,PHP_INT_MAX);task_check($attempts===array()&&task_manifest()===$before&&count($mail)===$n,'all '.count($before).' disposable tables unchanged by repeated reads');

$op=wp_generate_uuid4();$input=array('title'=>'Make repeatable safely','event_id'=>$plan,'assignment_mode'=>'person','due_at_local'=>'2030-10-22 12:00:00','repeatable_checklist_id'=>$checklist);$repeatable=task_ok(task_command('create',0,$input,array('operation'=>$op)),'atomic repeatable create');$definition=bvmgr_tasks_get_task_template($repeatable['task_template_id']);task_check($definition['due_mode']==='fixed_datetime'&&$definition['due_time_local']==='12:00','repeatable preserves existing event-day due clock');$count=count(bvmgr_tasks_get_instances_for_event($plan));bvmgr_tasks_generate_for_event($plan);task_check(count(bvmgr_tasks_get_instances_for_event($plan))===$count,'new repeatable lineage does not duplicate current event task');$n=task_logs();task_ok(task_command('create',0,$input,array('operation'=>$op)),'repeatable replay');task_check(task_logs()===$n,'repeatable replay no new definition audit');

$invalid_plan=wp_insert_post(array('post_type'=>'vms_event_plan','post_status'=>'publish','post_title'=>'Missing occurrence queue fixture'));bvmgr_tasks_run_queued_event_generation($invalid_plan);task_check(get_post_meta($invalid_plan,'_vms_tasks_generation_queue_state',true)==='failed','invalid queued generation never falsely marked complete');
bvmgr_tasks_queue_generate_for_event($plan,1,'test_without_tickets');task_check((bool)wp_next_scheduled('vms_tasks_generate_for_event_queued',array($plan)),'non-ticketed task generation is queued');$n=count(bvmgr_tasks_get_instances_for_event($plan));bvmgr_tasks_run_queued_event_generation($plan);task_check(get_post_meta($plan,'_vms_tasks_generation_queue_state',true)==='complete'&&count(bvmgr_tasks_get_instances_for_event($plan))===$n,'queued replay no duplicate task');
wp_set_current_user($users['a']);$_GET['page']='vms-my-tasks';task_check(apply_filters('woocommerce_prevent_admin_access',true)===false,'Woo allows scoped self task screen');$_GET['page']='plugins';task_check(apply_filters('woocommerce_prevent_admin_access',true)===true,'Woo restriction retained elsewhere');wp_set_current_user(1);
// Terminal history, canceled-event retain policy, and a distinct repeated Event Plan.
$historical=task_ok(task_command('create',0,array('title'=>'Closed relative history','event_id'=>$plan,'timing'=>array('due_kind'=>'datetime','due_source'=>'event_offset','due_offset'=>-15))),'historical relative seed');task_ok(task_command('transition',$historical['id'],array('status'=>'done')),'close historical');$historical=bvmgr_tasks_get_instance($historical['id']);
bvmgr_event_occurrence_authorized_write(static fn()=>update_post_meta($plan,'_vms_event_date','2030-10-23'));clean_post_cache($plan);bvmgr_tasks_reconcile_event($plan);task_check(bvmgr_tasks_get_instance($historical['id'])===$historical,'completed relative history never moves');
$retain=task_ok(task_command('create',0,array('title'=>'Retained follow-up','event_id'=>$plan,'timing'=>array('cancellation_policy'=>'retain'))),'retain policy seed');update_post_meta($plan,'_vms_event_plan_status','cancelled');bvmgr_tasks_reconcile_event($plan);task_check(bvmgr_tasks_get_instance($retain['id'])['status']==='open'&&bvmgr_tasks_sync_record($retain['id'])['review']==='','retained follow-up survives cancellation deliberately');update_post_meta($plan,'_vms_event_plan_status','ready');
$copy=wp_insert_post(array('post_type'=>'vms_event_plan','post_status'=>'publish','post_title'=>'Distinct repeated event'));foreach(array('_vms_event_date'=>'2030-10-24','_vms_start_time'=>'20:00','_vms_end_time'=>'23:00','_vms_event_plan_status'=>'ready') as $k=>$v)bvmgr_event_occurrence_authorized_write(static fn()=>update_post_meta($copy,$k,$v));bvmgr_tasks_generate_for_event($copy);$copy_task=$wpdb->get_row($wpdb->prepare('SELECT * FROM %i WHERE event_id=%d AND task_template_id=%d',bvmgr_tasks_table_name('task_instances'),$copy,$template),ARRAY_A);task_check($copy_task&&(int)$copy_task['id']!==(int)$g['id'],'different Event Plan gets distinct task identity');$wpdb->delete(bvmgr_tasks_table_name('task_templates'),array('id'=>$template));bvmgr_tasks_generate_for_event($copy);task_check(bvmgr_tasks_get_instance($copy_task['id'])===$copy_task,'deleted template never deletes or rewrites operational snapshot');
// Unlocked scheduled responsibility clears on ambiguity; an explicit manager lock is retained.
wp_set_post_terms($staff['b'],array($role),'vms_staff_role');$wpdb->update(bvmgr_staffing_table_name('assignments'),array('status'=>'confirmed'),array('assignment_id'=>$assignment));$wpdb->insert(bvmgr_staffing_table_name('assignments'),array('slot_id'=>$slot,'staff_id'=>$staff['b'],'status'=>'confirmed','created_at'=>$now,'updated_at'=>$now));$second=(int)$wpdb->insert_id;task_check(bvmgr_tasks_scheduled_person($plan,$slug)['status']==='multiple','multiple confirmed people remain explicitly unresolved');
$locked=task_ok(task_command('create',0,array('title'=>'Locked role owner','event_id'=>$plan,'assignment_mode'=>'scheduled_role','role_key'=>$slug,'assignee_user_id'=>$users['a'],'assignment_locked'=>1)),'locked role seed');bvmgr_tasks_reconcile_event($plan);task_check((int)bvmgr_tasks_get_instance($locked['id'])['assignee_user_id']===$users['a']&&empty(bvmgr_tasks_get_instance($role_task['id'])['assignee_user_id']),'ambiguity clears unlocked task and preserves manual lock');

wp_set_current_user($users['a']);$_GET=array('page'=>'vms-my-tasks');ob_start();bvmgr_tasks_render_my_tasks_page();$html=ob_get_clean();task_check(str_contains($html,'All open')&&str_contains($html,'Locked role owner'),'default My Tasks includes assigned work without due dates');wp_set_current_user(1);
