<?php
/** Real SQL and transport interception; hard-bound disposable database only. */
require __DIR__ . '/bootstrap.php';
$checks = 0; $mail = array(); $transport = 'success';
function sn_check(bool $ok, string $label): void { global $checks; if (!$ok) throw new RuntimeException($label); $checks++; }
function sn_count(): int { global $wpdb; return (int) $wpdb->get_var("SELECT COUNT(*) FROM {$wpdb->prefix}vms_notify_log WHERE source='vms_staffing'"); }
function sn_latest(int $plan): array { $a = bvmgr_staffing_notify_audits($plan); return bvmgr_staffing_notify_logs(bvmgr_staffing_notify_key((int) $a[0]['log_id']))[0] ?? array(); }
function sn_age(int $plan): void { global $wpdb; $r=sn_latest($plan); $wpdb->update(bvmgr_notify_log_table_name(),array('created_at'=>gmdate('Y-m-d H:i:s',time()-65)),array('id'=>$r['id'])); }
function sn_transition(array $f,string $target,array $more=array()): array { $r=bvmgr_staffing_lifecycle_row($f['id']);return bvmgr_staffing_transition_assignment($f['id'],$target,array_merge(array('context'=>'operator','event_plan_id'=>$f['plan'],'revision'=>$r['revision'],'operation_id'=>wp_generate_uuid4(),'reason'=>'Phase 3C test'),$more)); }
function sn_fixture(string $email='delivery@example.invalid'): array {
 global $wpdb;
 $plan=wp_insert_post(array('post_type'=>'vms_event_plan','post_status'=>'publish','post_title'=>'Notification fixture '.wp_generate_uuid4()));
 foreach(array('_vms_event_date'=>'2030-10-20','_vms_start_time'=>'12:00','_vms_end_time'=>'18:00','_vms_event_plan_status'=>'confirmed') as $k=>$v)update_post_meta($plan,$k,$v);
 $staff=wp_insert_post(array('post_type'=>'vms_staff','post_status'=>'publish','post_title'=>'Notification staff'));
 $user=wp_insert_user(array('user_login'=>'notif-'.wp_generate_uuid4(),'user_pass'=>wp_generate_password(40),'user_email'=>$email,'role'=>'subscriber'));
 sn_check(!is_wp_error($user),'fixture user: '.(is_wp_error($user)?$user->get_error_message():''));
 update_post_meta($staff,'_vms_linked_user_id',$user);update_user_meta($user,'_vms_staff_id',$staff);
 $term=wp_insert_term('Notification role '.wp_generate_uuid4(),'vms_staff_role');$role=(int)$term['term_id'];wp_set_post_terms($staff,array($role),'vms_staff_role');
 $now=bvmgr_staffing_now_mysql_utc();$wpdb->insert(bvmgr_staffing_table_name('event_slots'),array('event_plan_id'=>$plan,'role_id'=>$role,'headcount_needed'=>1,'shift_time_mode'=>'absolute','shift_start_local'=>'12:00','shift_end_local'=>'18:00','status'=>'active','created_at'=>$now,'updated_at'=>$now));$slot=(int)$wpdb->insert_id;
 $r=bvmgr_staffing_atomic(static function()use($slot,$staff){bvmgr_staffing_matrix_proposals($slot,array($staff));bvmgr_staffing_sync_lifecycle_window($slot);return array('ok'=>true);});sn_check(!empty($r['ok']),'proposal committed');
 $id=(int)$wpdb->get_var($wpdb->prepare('SELECT assignment_id FROM %i WHERE slot_id=%d',bvmgr_staffing_table_name('assignments'),$slot));return compact('plan','staff','user','slot','role','id');
}
sn_check(bvmgr_staffing_migrate_lifecycle()['ok'],'lifecycle schema');
$before=sn_count();$old=sn_fixture('historical@example.invalid');sn_check(sn_count()===$before,'disabled has no queue');sn_check(bvmgr_staffing_notify_enable(),'explicit enable');$floor=bvmgr_staffing_notify_floor();sn_check(bvmgr_staffing_notify_enable()&&bvmgr_staffing_notify_floor()===$floor,'enable idempotent');bvmgr_staffing_notify_tick();sn_check(sn_count()===$before,'historical transitions excluded');
add_filter('query',static function($sql){if(bvmgr_staffing_transaction_active()&&preg_match('/^INSERT INTO .*vms_notify_log/',$sql))throw new RuntimeException('notification write inside transaction');return $sql;},PHP_INT_MAX);
add_filter('pre_wp_mail',static function($pre,$m)use(&$mail,&$transport){
 if(!str_starts_with($m['subject'],'Staffing update:'))return false;
 sn_check(!bvmgr_staffing_transaction_active(),'mail after transaction');global $wpdb;
 $reader=new wpdb(DB_USER,DB_PASSWORD,DB_NAME,DB_HOST);
 $latest=$reader->get_row("SELECT * FROM {$wpdb->prefix}vms_notify_log WHERE source='vms_staffing' ORDER BY id DESC LIMIT 1",ARRAY_A);$payload=json_decode($latest['payload_json'],true);
 sn_check($payload['phase']==='attempt','attempt durable before mail');
 sn_check((int)$reader->get_var($reader->prepare('SELECT COUNT(*) FROM %i WHERE log_id=%d',bvmgr_staffing_table_name('audit'),$payload['audit_id']))===1,'independent connection sees committed audit');$reader->close();
 $mail[]=$m;if($transport==='throw')throw new RuntimeException('unknown delivery');return $transport!=='failure';
},PHP_INT_MAX,2);
$f=sn_fixture();sn_check(count($mail)===1,'new proposal mail');sn_check($mail[0]['to']==='delivery@example.invalid','canonical recipient');sn_check(str_contains($mail[0]['message'],'2030-10-20')&&str_contains($mail[0]['message'],'propos')&&str_contains($mail[0]['message'],'assignment_id='),'context and safe landing');sn_check(sn_latest($f['plan'])['status']==='sent','sent audit');
$n=count($mail);bvmgr_staffing_notify_tick();bvmgr_staffing_notify_tick();sn_check(count($mail)===$n,'duplicate cron no send');
$row=bvmgr_staffing_lifecycle_row($f['id']);$op=array('context'=>'operator','event_plan_id'=>$f['plan'],'revision'=>$row['revision'],'operation_id'=>wp_generate_uuid4(),'reason'=>'test');
$r=bvmgr_staffing_transition_assignment($f['id'],'confirmed',$op);sn_check($r['ok']&&count($mail)===$n+1,'confirmed sends');$r=bvmgr_staffing_transition_assignment($f['id'],'confirmed',$op);sn_check($r['ok']&&!empty($r['noop'])&&count($mail)===$n+1,'same operation replay dedupe');
$n=count($mail);$logs=sn_count();sn_check(!sn_transition($f,'declined')['ok']&&sn_count()===$logs&&count($mail)===$n,'failed transition no mail/work');
sn_check(sn_transition($f,'canceled')['ok']&&count($mail)===$n+1,'cancellation');sn_check(sn_transition($f,'proposed')['ok'],'reproposal');
wp_set_current_user($f['user']);$row=bvmgr_staffing_lifecycle_row($f['id']);$req=array('assignment_id'=>(string)$f['id'],'event_plan_id'=>(string)$f['plan'],'revision'=>(string)$row['revision'],'target'=>'declined','operation_id'=>wp_generate_uuid4(),'nonce'=>wp_create_nonce(bvmgr_staffing_lifecycle_nonce($f['id'],'declined',(int)$row['revision'],'staff')));
$n=count($mail);sn_check(bvmgr_staffing_handle_lifecycle_request($req,'staff','POST')['ok']&&count($mail)===$n+1,'staff decline and follow-up');sn_check(bvmgr_staffing_handle_lifecycle_request($req,'staff','POST')['noop']&&count($mail)===$n+1,'staff response replay');sn_check(!bvmgr_staffing_handle_lifecycle_request($req,'staff','GET')['ok'],'GET cannot respond');$bad=$req;$bad['nonce']='invalid';sn_check(!bvmgr_staffing_handle_lifecycle_request($bad,'staff','POST')['ok'],'invalid nonce');
wp_set_current_user(1);sn_check(sn_transition($f,'proposed')['ok'],'restore decline');wp_set_current_user($f['user']);$stale=$req;$stale['operation_id']=wp_generate_uuid4();sn_check(!bvmgr_staffing_handle_lifecycle_request($stale,'staff','POST')['ok'],'stale response denied');wp_set_current_user(1);
$transport='failure';$n=count($mail);sn_check(sn_transition($f,'confirmed')['ok'],'failure does not roll back');sn_check(bvmgr_staffing_lifecycle_row($f['id'])['status']==='confirmed'&&sn_latest($f['plan'])['status']==='failed','staffing committed, failure audited');$key=sn_latest($f['plan'])['event_key'];bvmgr_staffing_notify_tick();sn_check(count($mail)===$n+1,'retry cooldown');sn_age($f['plan']);$transport='success';bvmgr_staffing_notify_tick();sn_check(sn_latest($f['plan'])['status']==='sent'&&sn_latest($f['plan'])['event_key']===$key,'retry same identity success');$n=count($mail);bvmgr_staffing_notify_tick();sn_check(count($mail)===$n,'successful retry dedupe');
$transport='failure';sn_transition($f,'canceled');$oldkey=sn_latest($f['plan'])['event_key'];sn_age($f['plan']);$transport='success';sn_transition($f,'proposed');sn_check(bvmgr_staffing_notify_logs($oldkey)[0]['status']==='skipped','stale cancellation retry suppressed');
$transport='throw';sn_transition($f,'confirmed');sn_check(json_decode(sn_latest($f['plan'])['payload_json'],true)['phase']==='attempt','unknown outcome durable');$n=count($mail);$transport='success';bvmgr_staffing_notify_tick();bvmgr_staffing_notify_tick($f['plan'],(int)json_decode(sn_latest($f['plan'])['payload_json'],true)['audit_id']);sn_check(count($mail)===$n,'unknown outcome never auto or manual resent');
$missing=sn_fixture('');sn_check(sn_latest($missing['plan'])['status']==='failed','missing email visible');sn_check(bvmgr_staffing_lifecycle_row($missing['id'])['status']==='proposed','missing email does not roll back');
wp_update_user(array('ID'=>$missing['user'],'user_email'=>'repaired@example.invalid'));sn_age($missing['plan']);bvmgr_staffing_notify_tick();sn_check(sn_latest($missing['plan'])['status']==='sent','missing email repair safe retry');
$filter=static function($sql){return str_starts_with($sql,'INSERT INTO `'.bvmgr_notify_log_table_name().'`')?'INVALID SQL QUEUE FAILURE':$sql;};add_filter('query',$filter,999);$q=sn_fixture('queue@example.invalid');remove_filter('query',$filter,999);sn_check(!sn_latest($q['plan']),'queue failure recoverable from committed audit');bvmgr_staffing_notify_tick();sn_check(sn_latest($q['plan'])['status']==='sent','crash/queue insertion recovery');
$template=static function($pre,$event){if($event==='staffing_assignment_changed')throw new RuntimeException('template failure');return $pre;};add_filter('vms_notify_template_payload',$template,10,2);sn_transition($q,'confirmed');remove_filter('vms_notify_template_payload',$template,10);sn_check(sn_latest($q['plan'])['error_message']==='template_render_failed','template failure persisted');sn_age($q['plan']);bvmgr_staffing_notify_tick();sn_check(sn_latest($q['plan'])['status']==='sent','template retry');
$invalid=sn_fixture('invalid-original@example.invalid');$wpdb->update($wpdb->users,array('user_email'=>'bad@@example.invalid'),array('ID'=>$invalid['user']));clean_user_cache($invalid['user']);sn_transition($invalid,'confirmed');sn_check(sn_latest($invalid['plan'])['error_message']==='invalid_email','malformed email rejected without repair');
$exhaust=sn_fixture('');sn_age($exhaust['plan']);bvmgr_staffing_notify_tick();sn_age($exhaust['plan']);bvmgr_staffing_notify_tick();$last=sn_latest($exhaust['plan']);sn_check((int)json_decode($last['payload_json'],true)['attempts']===3,'automatic retry cap');$n=sn_count();sn_age($exhaust['plan']);bvmgr_staffing_notify_tick();sn_check(sn_count()===$n,'exhausted record not retried automatically');wp_update_user(array('ID'=>$exhaust['user'],'user_email'=>'exhaustion-repaired@example.invalid'));bvmgr_staffing_notify_tick($exhaust['plan'],(int)json_decode($last['payload_json'],true)['audit_id']);sn_check(sn_latest($exhaust['plan'])['status']==='sent','explicit reviewed retry after correction');
update_user_meta($exhaust['user'],'vms_notify_email_enabled',0);sn_transition($exhaust,'confirmed');sn_check(sn_latest($exhaust['plan'])['error_message']==='email_channel_disabled','existing email preference respected');
// Audited schedule change is a separate logical committed fact.
$prior=sn_count();$r=bvmgr_staffing_atomic(static function()use($q,$wpdb){$wpdb->update(bvmgr_staffing_table_name('event_slots'),array('shift_start_local'=>'13:00'),array('slot_id'=>$q['slot']));bvmgr_staffing_sync_lifecycle_window($q['slot']);return array('ok'=>true);});sn_check($r['ok']&&sn_count()>$prior&&sn_latest($q['plan'])['status']==='sent','shift revision delivered after commit');
$prior=sn_count();$r=bvmgr_staffing_atomic(static function()use($q,$wpdb){$wpdb->update(bvmgr_staffing_table_name('event_slots'),array('shift_start_local'=>'14:00'),array('slot_id'=>$q['slot']));bvmgr_staffing_sync_lifecycle_window($q['slot']);throw new RuntimeException('rollback');});sn_check(!$r['ok']&&sn_count()===$prior,'rolled back window no notification');
$n=count($mail);$prior=sn_count();ob_start();bvmgr_staffing_notify_render($q['plan'],true);bvmgr_staffing_notify_render($q['plan']);ob_end_clean();bvmgr_staffing_notify_recipient($q['staff']);sn_check(sn_count()===$prior&&count($mail)===$n,'read rendering no queue/mail');
// Independent PHP workers race canonical transitions and queue recovery.
function sn_race(array $jobs): array {
 $dir=sys_get_temp_dir().'/bvm-notify-race-'.wp_generate_uuid4();mkdir($dir);$procs=array();$pipes=array();$results=array();
 try {
  foreach($jobs as $i=>$job){$job['mail_log']=$dir.'/mail';$job['go']=$dir.'/go';file_put_contents($dir.'/job'.$i,json_encode($job));$procs[$i]=proc_open(array(PHP_BINARY,__DIR__.'/notification-worker.php',$dir.'/job'.$i,$dir.'/ready'.$i),array(0=>array('pipe','r'),1=>array('pipe','w'),2=>array('pipe','w')),$pipes[$i]);fclose($pipes[$i][0]);}
  $deadline=microtime(true)+10;do{$ready=true;foreach($jobs as $i=>$job)$ready=$ready&&is_file($dir.'/ready'.$i);if(!$ready)usleep(10000);}while(!$ready&&microtime(true)<$deadline);
  sn_check($ready,'independent workers ready');file_put_contents($dir.'/go','go');
  foreach($procs as $i=>$proc){$out=stream_get_contents($pipes[$i][1]);$err=stream_get_contents($pipes[$i][2]);fclose($pipes[$i][1]);fclose($pipes[$i][2]);$exit=proc_close($proc);sn_check($exit===0||!empty($jobs[$i]['crash'])&&$exit===23,'worker exit '.$err);$results[]=json_decode($out,true);}
  $count=is_file($dir.'/mail')?count(file($dir.'/mail',FILE_IGNORE_NEW_LINES)):0;return array($results,$count);
 } finally {foreach(glob($dir.'/*') as $file)unlink($file);rmdir($dir);}
}
$race=sn_fixture('race-delivery@example.invalid');$row=bvmgr_staffing_lifecycle_row($race['id']);$opts=array('context'=>'operator','event_plan_id'=>$race['plan'],'revision'=>$row['revision'],'operation_id'=>wp_generate_uuid4(),'reason'=>'race');$job=array('kind'=>'transition','id'=>$race['id'],'target'=>'confirmed','options'=>$opts);
[$out,$sent]=sn_race(array($job,$job));sn_check($out[0]['ok']&&$out[1]['ok']&&$sent===1,'concurrent duplicate request sends once');sn_check(count(array_filter($out,static fn($r)=>!empty($r['noop'])))===1,'one concurrent noop');
$recover=static function($sql){return str_starts_with($sql,'INSERT INTO `'.bvmgr_notify_log_table_name().'`')?'INVALID SQL RECOVERY':$sql;};add_filter('query',$recover,999);$race2=sn_fixture('race-queue@example.invalid');remove_filter('query',$recover,999);
[$out,$sent]=sn_race(array(array('kind'=>'tick'),array('kind'=>'tick')));sn_check($sent===1&&sn_latest($race2['plan'])['status']==='sent','concurrent recovery workers send once');
add_filter('query',$recover,999);$crash=sn_fixture('crash@example.invalid');remove_filter('query',$recover,999);[$out,$sent]=sn_race(array(array('kind'=>'tick','crash'=>true)));sn_check($sent===1&&json_decode(sn_latest($crash['plan'])['payload_json'],true)['phase']==='attempt','worker process exit retains uncertain attempt');[$out,$sent]=sn_race(array(array('kind'=>'tick'),array('kind'=>'tick')));sn_check($sent===0,'worker restart cannot duplicate uncertain mail');
echo "PASS $checks staffing notification real-database assertions; ".count($mail)." intercepted attempts\n";
