<?php
declare(strict_types=1);

/**
 * Phase 4 direct first-party integration contracts.
 *
 * Production add-on source remains read-only. This manifest records the
 * frozen source selected for the disposable runtime and the observable
 * contracts that can be exercised without operational data or network I/O.
 */
return array(
	'plugins' => array(
		'drm-calendar-intake' => array(
			'name' => 'DRM Calendar Intake',
			'version' => '0.2.4',
			'entry' => 'drm-calendar-intake/drm-calendar-intake.php',
			'dependency' => 'administrative integration only',
			'companions' => array('required' => array(), 'optional' => array()),
			'marker' => array('constant' => 'DRM_CI_VERSION', 'value' => '0.2.4'),
			'detection' => array("post_type_exists('vms_event_plan')"),
			'functions' => array(),
			'classes' => array(),
			'constants' => array(),
			'hook_callbacks' => array(),
			'menus' => array(
				array('parent' => 'edit.php?post_type=drm_calendar_item', 'slug' => 'drm-calendar-intake-settings', 'capability' => 'manage_options'),
				array('parent' => 'edit.php?post_type=drm_calendar_item', 'slug' => 'drm-calendar-intake-migration-review', 'capability' => 'manage_options'),
				array('parent' => 'edit.php?post_type=drm_calendar_item', 'slug' => 'drm-calendar-intake-venues', 'capability' => 'manage_options'),
			),
			'fallback_menus' => array('same_as_bvm' => true),
			'notice' => array('present' => '', 'absent' => 'VMS does not appear active'),
			'post_types' => array('drm_calendar_item', 'vms_event_plan'),
			'taxonomies' => array(),
			'meta' => array(),
			'options' => array('drm_calendar_intake_settings', 'drm_calendar_intake_auth', 'drm_calendar_intake_sync', 'drm_calendar_intake_sources', 'drm_calendar_intake_venues'),
			'tables' => array(),
			'rest_namespaces' => array(),
			'ajax_actions' => array(),
			'cron_hooks' => array('drm_calendar_intake_automatic_sync'),
		),
		'vms-commerce-discounts' => array(
			'name' => 'VMS Commerce Discounts',
			'version' => '0.2.11',
			'entry' => 'vms-commerce-discounts/vms-commerce-discounts.php',
			'dependency' => 'data-contract only',
			'companions' => array('required' => array('woocommerce', 'woocommerce-square'), 'optional' => array('the-events-calendar', 'event-tickets', 'event-tickets-plus')),
			'marker' => array('constant' => 'VMS_DISCOUNTS_VERSION', 'value' => '0.2.11'),
			'detection' => array('No BVM identity check; reads BVM-shaped post/meta contracts.'),
			'functions' => array(),
			'classes' => array(),
			'constants' => array(),
			'hook_callbacks' => array(),
			'menus' => array(array('parent' => 'woocommerce', 'slug' => 'vms-commerce-discounts', 'capability' => 'manage_options')),
			'fallback_menus' => array('without_woocommerce' => 'none'),
			'notice' => array('present' => '', 'missing_companion' => 'requires WooCommerce to be active', 'missing_square' => 'fatal before a native notice can register'),
			'post_types' => array('vms_event_plan', 'tribe_events', 'product'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_plan_id', '_vms_product_role', '_vms_entitlement_event_id', '_vms_event_id', '_vms_parent_event_id'),
			'options' => array('vms_discounts_global_enabled', 'vms_discounts_global_rules'),
			'tables' => array(),
			'rest_namespaces' => array(),
			'ajax_actions' => array('vms_discounts_search_products', 'vms_discounts_set_tip'),
			'cron_hooks' => array(),
		),
		'vms-investor-portal' => array(
			'name' => 'VMS Investor Portal',
			'version' => '0.2.2',
			'entry' => 'vms-investor-portal/vms-investor-portal.php',
			'dependency' => 'optional',
			'companions' => array('required' => array(), 'optional' => array('woocommerce', 'the-events-calendar', 'vms-data-tools', 'vms-ops-console-premium')),
			'marker' => array('constant' => 'VMS_INVESTOR_PORTAL_VERSION', 'value' => '0.2.2'),
			'detection' => array('vms_register_admin_page()', 'vms_admin_menu_parent_slug()', "parent menu 'vms-dashboard'"),
			'functions' => array('vms_admin_menu_parent_slug', 'vms_admission_table_entries', 'vms_event_command_center_get_ticket_reporting_truth', 'vms_event_command_center_get_ticket_snapshot', 'vms_event_command_center_get_ticket_snapshot_light', 'vms_event_plan_get_status', 'vms_event_plan_status_normalize', 'vms_get_event_plan_for_tec_event', 'vms_goals_get_default_direct_costs_cents', 'vms_goals_get_overhead_allocated_cents', 'vms_goals_get_settings', 'vms_meta_key', 'vms_register_admin_page', 'vms_staffing_get_event_plan_headcount_context', 'vms_ticket_revenue_build_report', 'vms_ticket_revenue_plan_tec_meta_key', 'vms_ticketing_v2_find_plan_id_by_tec_event', 'vms_ticketing_v2_find_plan_id_by_tec_event_id'),
			'companion_functions' => array('vms_dt_reporting_build_event_model', 'vms_dt_reporting_profitability_ad_spend_data', 'vms_ops_table_pc_scan_log', 'vms_ops_ticket_get_event_attendees', 'vms_ops_ticket_resolve_event_plan_id_for_guest_list'),
			'classes' => array(),
			'constants' => array('VMS_PLUGIN_PATH'),
			'hook_callbacks' => array('vms_admin_register_pages' => array('VMS_Investor_Portal', 'register_vms_admin_page')),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-investor-portal', 'capability' => 'vms_manage_investor_financials')),
			'fallback_menus' => array('top' => 'vms-investor-portal'),
			'notice' => array('present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_event', 'tribe_events'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_plan_status', '_vms_tec_event_id', '_vms_event_plan_id', '_vms_true_headcount'),
			'options' => array('vms_investor_portal_db_version'),
			'tables' => array('vms_investor_event_financials'),
			'rest_namespaces' => array(),
			'ajax_actions' => array(),
			'cron_hooks' => array(),
		),
		'vms-meta-ads' => array(
			'name' => 'VMS Meta Ads Builder',
			'version' => '0.1.106',
			'entry' => 'vms-meta-ads/vms-meta-ads.php',
			'dependency' => 'required',
			'companions' => array('required' => array(), 'optional' => array()),
			'marker' => array('constant' => 'VMS_MA_VERSION', 'value' => '0.1.106'),
			'detection' => array('vms_register_module()', 'vms_module_is_registered()', 'vms_module_is_enabled()'),
			'functions' => array('vms_enqueue_tour_assets', 'vms_event_plan_get_status', 'vms_meta_key', 'vms_module_is_enabled', 'vms_module_is_registered', 'vms_register_module', 'vms_venue_meta_key'),
			'classes' => array(),
			'constants' => array('VMS_PLUGIN_PATH', 'VMS_PLUGIN_URL', 'VMS_VERSION'),
			'guarded_constants' => array('VMS_CAP_MANAGE', 'VMS_CAP_MANAGE_EVENT_PLANS', 'VMS_CAP_MANAGE_VMS', 'VMS_CAP_SOCIAL_MANAGE'),
			'hook_callbacks' => array('vms_register_docs_sources' => array('VMS_Meta_Ads', 'register_docs_source'), 'vms_register_tours' => array('VMS_Meta_Ads_Tours', 'register_tour')),
			'menus' => array(
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-builder', 'capability' => 'vms_social_manage'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-promote', 'capability' => 'vms_social_manage'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-performance', 'capability' => 'vms_social_manage'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-logs', 'capability' => 'vms_social_manage'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-settings', 'capability' => 'vms_social_manage'),
			),
			'fallback_menus' => array('without_bvm' => 'none'),
			'notice' => array('present' => '', 'absent' => 'VMS core module system is unavailable'),
			'post_types' => array('vms_event_plan', 'vms_venue'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_plan_status', '_vms_tec_event_id', '_vms_venue_id', '_vms_ticket_url'),
			'options' => array('vms_ma_settings', 'vms_ma_db_version'),
			'tables' => array('vms_meta_ads_builds', 'vms_meta_ads_templates', 'vms_meta_ads_tiers', 'vms_meta_ads_audit'),
			'rest_namespaces' => array('vms-ma/v1'),
			'ajax_actions' => array('vms_api_copy_bundle', 'vms_api_diag_panel_html'),
			'cron_hooks' => array('vms_ma_budget_sync_cron', 'vms_api_attempts_prune_daily'),
		),
		'vms-ops-console-premium' => array(
			'name' => 'VMS Ops Console Premium',
			'version' => '0.1.66',
			'entry' => 'vms-ops-console-premium/vms-ops-console-premium.php',
			'dependency' => 'optional',
			'companions' => array('required' => array(), 'optional' => array('woocommerce', 'event-tickets', 'vms-season-passes')),
			'marker' => array('constant' => 'VMS_OPS_CONSOLE_VERSION', 'value' => '0.1.66'),
			'detection' => array('function_exists() guards around BVM APIs', "parent menu 'vms-dashboard'"),
			'functions' => array('vms_admin_ui_data_tools_capability', 'vms_admin_ui_ops_capability', 'vms_admin_ui_registered_page_url', 'vms_admission_audit_log', 'vms_get_current_venue_id', 'vms_get_event_plan_for_tec_event', 'vms_meta_key', 'vms_pass_claims_get_batch_by_id'),
			'classes' => array(),
			'constants' => array(),
			'guarded_constants' => array('VMS_VENUE_TEMPLATE_META_KEY'),
			'hook_callbacks' => array('vms_addons_manifest_entries' => 'vms_ops_filter_addons_manifest_entries'),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-ops-console-members', 'capability' => 'vms_ops_manage_members_admin')),
			'fallback_menus' => array('without_bvm' => 'standalone ops pages remain available'),
			'notice' => array('present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_venue'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_plan_start_datetime', '_vms_venue_id', '_vms_staff_id', '_vms_linked_user_id'),
			'options' => array('vms_ops_db_version'),
			'tables' => array('vms_ops_members', 'vms_ops_visits', 'vms_ops_presence', 'vms_ops_pc_scan_log'),
			'rest_namespaces' => array('vms-ops/v1'),
			'ajax_actions' => array(),
			'cron_hooks' => array('vms_ops_presence_expire_event'),
		),
		'vms-safety-pro' => array(
			'name' => 'VMS Safety Toolkit Pro',
			'version' => '0.1.0',
			'entry' => 'vms-safety-pro/vms-safety-pro.php',
			'dependency' => 'required feature extension',
			'companions' => array('required' => array(), 'optional' => array()),
			'marker' => array('constant' => 'VMS_SAFETY_PRO_FILE', 'value' => null),
			'detection' => array('vms_safety_admin_url()', "post_type_exists('vms_doc')"),
			'functions' => array('vms_safety_admin_url', 'vms_safety_audit_log', 'vms_safety_manage_capability'),
			'classes' => array(),
			'constants' => array('VMS_CAP_SAFETY_TEMPLATES'),
			'hook_callbacks' => array('vms_safety_admin_tabs' => 'vms_safety_pro_register_tabs', 'vms_safety_render_tab_templates' => 'vms_safety_pro_render_templates_tab', 'vms_safety_render_tab_agreements' => 'vms_safety_pro_render_agreements_tab'),
			'menus' => array(),
			'fallback_menus' => array('without_bvm' => 'none; hooks remain inert'),
			'notice' => array('present' => '', 'absent' => ''),
			'post_types' => array('vms_doc'),
			'taxonomies' => array(),
			'meta' => array(),
			'options' => array(),
			'tables' => array(),
			'rest_namespaces' => array(),
			'ajax_actions' => array(),
			'cron_hooks' => array(),
		),
		'vms-season-passes' => array(
			'name' => 'VMS Season Passes',
			'version' => '0.1.0',
			'entry' => 'vms-season-passes/vms-season-passes.php',
			'dependency' => 'required',
			'companions' => array('required' => array(), 'optional' => array('woocommerce', 'vms-ops-console-premium')),
			'marker' => array('constant' => 'VMS_SEASON_PASSES_VERSION', 'value' => '0.1.0'),
			'detection' => array('VMS_VERSION >= 1.1.0', 'vms_register_module()'),
			'functions' => array('vms_admin_ui_render_shell', 'vms_admission_normalize_email', 'vms_admission_normalize_name', 'vms_admission_normalize_phone', 'vms_get_event_plan_for_tec_event', 'vms_meta_key', 'vms_register_admin_page', 'vms_register_module'),
			'companion_functions' => array('vms_ops_hash_scan_payload', 'vms_ops_now_mysql', 'vms_ops_pc_log_scan_event', 'vms_ops_rest_error_from_wp_error', 'vms_ops_rest_ok', 'vms_ops_rest_resolve_venue_id', 'vms_ops_ticket_checkin_assert_window', 'vms_ops_ticket_get_event', 'vms_ops_ticket_is_pre_event_window_error', 'vms_ops_ticket_normalize_scan_reference'),
			'classes' => array(),
			'constants' => array('VMS_VERSION'),
			'hook_callbacks' => array('vms_admin_register_pages' => 'vms_season_passes_register_admin_page_metadata'),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-season-passes', 'capability' => 'vms_season_pass_manage')),
			'fallback_menus' => array('without_bvm' => 'none'),
			'notice' => array('present' => '', 'absent' => 'Activate Venue Management System first'),
			'post_types' => array('vms_event_plan'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_plan_id'),
			'options' => array('vms_season_passes_db_version'),
			'tables' => array('vms_season_pass_types', 'vms_season_passholders', 'vms_season_pass_checkins'),
			'rest_namespaces' => array(),
			'ajax_actions' => array(),
			'cron_hooks' => array(),
		),
		'vms-sponsorships' => array(
			'name' => 'VMS Sponsorships',
			'version' => '0.1.27',
			'entry' => 'vms-sponsorships/vms-sponsorships.php',
			'dependency' => 'optional',
			'companions' => array('required' => array(), 'optional' => array('the-events-calendar')),
			'marker' => array('constant' => 'VMS_SPONSORSHIPS_VERSION', 'value' => '0.1.27'),
			'detection' => array('BVM registry function_exists() checks', "parent menu 'vms-dashboard'"),
			'functions' => array('vms_admin_menu_parent_slug', 'vms_admin_ui_is_vms_screen', 'vms_admin_ui_page_url', 'vms_admin_ui_render_top_nav', 'vms_event_details_before_commerce_priority', 'vms_event_details_commerce_hook', 'vms_register_admin_page'),
			'guarded_functions' => array('vms_admin_registry_has_parent_menu', 'vms_admin_registry_is_available', 'vms_admin_registry_parent_slug', 'vms_admin_registry_should_render_fallback_nav'),
			'classes' => array(),
			'constants' => array(),
			'hook_callbacks' => array('vms_admin_register_pages' => array('VMS_Sponsorships_Admin', 'register_vms_admin_pages'), 'vms_event_plan_after_modules' => array('VMS_Sponsorships_Event_Plans', 'render_vms_event_plan_card')),
			'menus' => array(
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships', 'capability' => 'manage_options'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-applications', 'capability' => 'manage_options'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-assignments', 'capability' => 'manage_options'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-packages', 'capability' => 'manage_options'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-assets', 'capability' => 'manage_options'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-visibility', 'capability' => 'manage_options'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-settings', 'capability' => 'manage_options'),
			),
			'fallback_menus' => array('top' => 'vms-sponsorships'),
			'notice' => array('present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_event', 'tribe_events'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_date', '_vms_expected_attendance', '_vms_sponsorship_price_multiplier', '_vms_sponsorship_value_tier'),
			'options' => array('vms_sponsorships_version', 'vms_sponsorships_seeded_defaults'),
			'tables' => array('vms_sponsorship_applications', 'vms_sponsorship_packages', 'vms_sponsorship_assignments', 'vms_sponsor_assets'),
			'rest_namespaces' => array(),
			'ajax_actions' => array(),
			'cron_hooks' => array(),
		),
		'vmsx-checkout-policies' => array(
			'name' => 'VMS Checkout Policies',
			'version' => '0.1.8',
			'entry' => 'vmsx-checkout-policies/vmsx-checkout-policies.php',
			'dependency' => 'optional administrative integration',
			'companions' => array('required' => array('woocommerce'), 'optional' => array()),
			'marker' => array('constant' => 'VMSX_CHECKOUT_POLICIES_VERSION', 'value' => '0.1.8'),
			'detection' => array('vms_render_settings_page()', 'VMS_VERSION'),
			'functions' => array('vms_ticketing_v2_meta_get', 'vms_ticketing_v2_product_meta_key'),
			'classes' => array(),
			'constants' => array('VMS_VERSION'),
			'hook_callbacks' => array(),
			'menus' => array(),
			'fallback_menus' => array('with_woocommerce_without_bvm' => 'vmsx-checkout-policies', 'without_woocommerce' => 'none'),
			'notice' => array('present' => '', 'absent' => ''),
			'post_types' => array('product'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_plan_id', '_vms_product_role'),
			'options' => array('vmsx_checkout_policies_settings'),
			'tables' => array(),
			'rest_namespaces' => array(),
			'ajax_actions' => array(),
			'cron_hooks' => array(),
		),
		'vmsx-weather-risk' => array(
			'name' => 'VMSX Weather Risk',
			'version' => '0.1.12',
			'entry' => 'vmsx-weather-risk/vmsx-weather-risk.php',
			'dependency' => 'required',
			'companions' => array('required' => array(), 'optional' => array('vms-data-tools')),
			'marker' => array('constant' => 'VMSX_WR_VERSION', 'value' => '0.1.12'),
			'detection' => array('VMS_PLUGIN_PATH', 'VMS_VERSION >= 0.2.24.505', 'vms_register_module()'),
			'functions' => array('vms_admin_ui_render_shell', 'vms_event_profitability_get_labor_cost_cents', 'vms_meta_key', 'vms_register_module', 'vms_sync_tec_venue_from_vms_venue'),
			'companion_functions' => array('vms_dt_reporting_build_ticket_pace_history', 'vms_dt_reporting_ticket_pace_closest_milestone', 'vms_dt_reporting_ticket_pace_projection', 'vms_dt_reporting_ticket_pace_rows'),
			'classes' => array(),
			'constants' => array('VMS_PLUGIN_PATH', 'VMS_VERSION'),
			'hook_callbacks' => array('vms_addons_manifest_entries' => array('VMSX_Weather_Risk', 'filter_manifest_entries'), 'vms_register_docs_sources' => array('VMSX_Weather_Risk', 'register_docs_source'), 'vms_admin_ui_nav_cluster_items' => array('VMSX_Weather_Risk_Admin_Menu', 'register_compact_nav_items'), 'vms_admin_ui_active_cluster' => array('VMSX_Weather_Risk_Admin_Menu', 'filter_active_cluster'), 'vms_admin_ui_shell_pages' => array('VMSX_Weather_Risk_Admin_Menu', 'register_shell_pages')),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-weather-risk', 'capability' => 'manage_options'), array('parent' => 'vms-dashboard', 'slug' => 'vms-weather-risk-settings', 'capability' => 'manage_options')),
			'fallback_menus' => array('without_bvm' => 'none'),
			'notice' => array('present' => '', 'absent' => 'requires the VMS core plugin'),
			'post_types' => array('vms_event_plan', 'vms_venue'),
			'taxonomies' => array(),
			'meta' => array('_vms_event_date', '_vms_start_time', '_vms_end_time', '_vms_venue_id', '_vms_ticket_stats_v1'),
			'options' => array('vmsx_weather_risk_settings', 'vmsx_weather_risk_log'),
			'tables' => array(),
			'rest_namespaces' => array(),
			'ajax_actions' => array('vmsx_weather_risk_refresh'),
			'cron_hooks' => array('vmsx_weather_risk_refresh_cron'),
		),
	),
	'blocked' => array(
		'drm-events-bridge' => array(
			'name' => 'DRM Events Bridge',
			'version' => '0.2.1',
			'entry' => 'drm-events-bridge/drm-events-bridge.php',
			'status' => 'BLOCKED — concurrent source movement',
			'reason' => 'Authoritative Git worktree has tracked modifications, deletions, and untracked files and is behind its remote.',
			'architecture' => 'DRM Event Router is authoritative; retained VMS mapping and gates are legacy/future enrichment, not a required local BVM runtime.',
			'functions' => array('vms_event_plan_status_normalize', 'vms_event_plan_statuses', 'vms_meta_key'),
			'post_types' => array('vms_event_plan', 'vms_vendor'),
			'meta' => array('_vms_event_plan_status'),
		),
	),
	'indirect' => array(
		'drm-event-router' => array('reason' => 'Produces the vms_projection payload but neither detects nor calls BVM runtime.'),
		'backstage-calendar-feeds' => array('reason' => 'Consumes DRM Calendar Intake provider contracts; no direct BVM runtime contract was found.'),
		'event-venue-map-modal' => array('reason' => 'Integrates with The Events Calendar presentation only; no direct BVM runtime contract was found.'),
	),
);
