<?php
declare(strict_types=1);

/**
 * Supported additional-suite profiles expressed as observable semantics.
 * Historical names are fallback evidence, never declarations required from BVM.
 */
$base = static function (array $overrides): array {
	return array_replace_recursive(array(
		'name' => '', 'version' => '', 'entry' => '', 'dependency' => 'optional',
		'companions' => array('required' => array(), 'optional' => array()),
		'marker' => array('constant' => '', 'value' => null),
		'capabilities' => array(), 'hooks' => array(), 'hook_callbacks' => array(),
		'menus' => array(), 'fallback_menus' => array(),
		'notice' => array('owner_patterns' => array(), 'present' => '', 'absent' => ''),
		'post_types' => array(), 'taxonomies' => array(), 'meta' => array(),
		'options' => array(), 'tables' => array(), 'rest_namespaces' => array(),
		'ajax_actions' => array(), 'cron_hooks' => array(),
	), $overrides);
};

$capability = static function (string $id, string $stage, string $canonicalProvider, string $legacyFallback, string $externalOwner, string $guard, string $outcome): array {
	return array(
		'id' => $id,
		'stage' => $stage,
		'canonical_provider' => $canonicalProvider,
		'legacy_fallback' => $legacyFallback,
		'external_dependency_owner' => $externalOwner,
		'guard' => $guard,
		'expected_outcome' => $outcome,
	);
};

$contracts = array(
	'profile' => 'mixed-additional-suite-remediation',
	'plugins' => array(
		'drm-calendar-intake' => $base(array(
			'name' => 'DRM Calendar Intake', 'version' => '0.2.4',
			'entry' => 'drm-calendar-intake/drm-calendar-intake.php',
			'dependency' => 'BVM enrichment optional; quarantine UI remains standalone',
			'marker' => array('constant' => 'DRM_CI_VERSION', 'value' => '0.2.4'),
			'capabilities' => array($capability('event-plan-discovery', 'feature path', "post_type_exists('vms_event_plan')", '', 'backstage-venue-manager', 'post-type presence guard', 'optional enrichment or standalone quarantine UI')),
			'menus' => array(
				array('parent' => 'edit.php?post_type=drm_calendar_item', 'slug' => 'drm-calendar-intake-settings', 'capability' => 'manage_options', 'registry' => false),
				array('parent' => 'edit.php?post_type=drm_calendar_item', 'slug' => 'drm-calendar-intake-migration-review', 'capability' => 'manage_options', 'registry' => false),
				array('parent' => 'edit.php?post_type=drm_calendar_item', 'slug' => 'drm-calendar-intake-venues', 'capability' => 'manage_options', 'registry' => false),
			),
			'fallback_menus' => array('same_without_bvm' => true),
			'notice' => array('owner_patterns' => array('DRM Calendar Intake', 'VMS does not appear active'), 'present' => '', 'absent' => 'VMS does not appear active'),
			'post_types' => array('drm_calendar_item', 'vms_event_plan'),
			'options' => array('drm_calendar_intake_settings', 'drm_calendar_intake_auth', 'drm_calendar_intake_sync', 'drm_calendar_intake_sources', 'drm_calendar_intake_venues'),
			'cron_hooks' => array('drm_calendar_intake_automatic_sync'),
		)),
		'vms-commerce-discounts' => $base(array(
			'name' => 'VMS Commerce Discounts', 'version' => '0.2.13',
			'entry' => 'vms-commerce-discounts/vms-commerce-discounts.php',
			'dependency' => 'WooCommerce required; WooCommerce Square optional',
			'companions' => array('required' => array('woocommerce'), 'optional' => array('woocommerce-square', 'the-events-calendar', 'event-tickets', 'event-tickets-plus')),
			'marker' => array('constant' => 'VMS_DISCOUNTS_VERSION', 'value' => '0.2.13'),
			'capabilities' => array(
				$capability('commerce-runtime', 'bootstrap', 'WooCommerce', '', 'woocommerce', 'required-dependency guard', 'clean inactive state without WooCommerce'),
				$capability('square-bridge', 'feature path', 'WooCommerce\\Square', '', 'woocommerce-square', 'optional class guard', 'non-Square runtime remains available with targeted warning'),
			),
			'menus' => array(array('parent' => 'woocommerce', 'slug' => 'vms-commerce-discounts', 'capability' => 'manage_options', 'registry' => false)),
			'fallback_menus' => array('without_woocommerce' => 'none'),
			'notice' => array('owner_patterns' => array('VMS Commerce Discounts', 'Commerce Discounts', 'WooCommerce Square integration'), 'present' => '', 'absent' => '', 'missing_companion' => 'requires WooCommerce to be active', 'missing_square' => 'WooCommerce Square integration is unavailable'),
			'post_types' => array('vms_event_plan', 'tribe_events', 'product'),
			'meta' => array('_vms_event_plan_id', '_vms_product_role', '_vms_entitlement_event_id', '_vms_event_id', '_vms_parent_event_id'),
			'options' => array('vms_discounts_global_enabled', 'vms_discounts_global_rules'),
			'ajax_actions' => array('vms_discounts_search_products', 'vms_discounts_set_tip'),
		)),
		'vms-investor-portal' => $base(array(
			'name' => 'VMS Investor Portal', 'version' => '0.2.3',
			'entry' => 'vms-investor-portal/vms-investor-portal.php',
			'dependency' => 'BVM optional; canonical registry preferred',
			'companions' => array('required' => array(), 'optional' => array('woocommerce', 'the-events-calendar', 'vms-data-tools', 'vms-ops-console-premium')),
			'marker' => array('constant' => 'VMS_INVESTOR_PORTAL_VERSION', 'value' => '0.2.3'),
			'capabilities' => array(
				$capability('admin-registry', 'registration', 'bvmgr_register_admin_page', 'vms_register_admin_page', 'backstage-venue-manager', 'canonical-first resolver; standalone fallback', 'canonical registry entry under BVM'),
				$capability('event-plan-meta', 'feature path', 'bvmgr_meta_key', 'vms_meta_key', 'backstage-venue-manager', 'canonical-first with stored-key fallback', 'financial views use BVM event contracts'),
			),
			'hooks' => array(array('name' => 'vms_admin_register_pages', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => array('VMS_Investor_Portal', 'register_vms_admin_page'))),
			'hook_callbacks' => array('vms_admin_register_pages' => array('VMS_Investor_Portal', 'register_vms_admin_page')),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-investor-portal', 'capability' => 'vms_manage_investor_financials', 'registry' => true, 'callback_method' => 'render_admin_page')),
			'fallback_menus' => array('top' => 'vms-investor-portal'),
			'notice' => array('owner_patterns' => array('VMS Investor Portal'), 'present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_event', 'tribe_events'),
			'meta' => array('_vms_event_plan_status', '_vms_tec_event_id', '_vms_event_plan_id', '_vms_true_headcount'),
			'options' => array('vms_investor_portal_db_version'), 'tables' => array('vms_investor_event_financials'),
		)),
		'vms-meta-ads' => $base(array(
			'name' => 'VMS Meta Ads Builder', 'version' => '0.1.107',
			'entry' => 'vms-meta-ads/vms-meta-ads.php', 'dependency' => 'BVM module system required',
			'marker' => array('constant' => 'VMS_MA_VERSION', 'value' => '0.1.107'),
			'capabilities' => array(
				$capability('module-registration', 'registration', 'bvmgr_register_module', 'vms_register_module', 'backstage-venue-manager', 'canonical-first resolver', 'registered and enabled under canonical BVM'),
				$capability('module-enablement', 'feature path', 'bvmgr_module_is_enabled', 'vms_module_is_enabled', 'backstage-venue-manager', 'canonical-first resolver', 'BVM-dependent UI enabled only with core'),
			),
			'hooks' => array(
				array('name' => 'vms_register_docs_sources', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => array('VMS_Meta_Ads', 'register_docs_source')),
				array('name' => 'vms_register_tours', 'kind' => 'filter', 'emission' => 'bvm-emitted', 'callback' => array('VMS_Meta_Ads_Tours', 'register_tour')),
			),
			'hook_callbacks' => array('vms_register_docs_sources' => array('VMS_Meta_Ads', 'register_docs_source'), 'vms_register_tours' => array('VMS_Meta_Ads_Tours', 'register_tour')),
			'menus' => array(
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-builder', 'capability' => 'vms_social_manage', 'registry' => false),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-promote', 'capability' => 'vms_social_manage', 'registry' => false),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-performance', 'capability' => 'vms_social_manage', 'registry' => false),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-logs', 'capability' => 'vms_social_manage', 'registry' => false),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-ma-ads-settings', 'capability' => 'vms_social_manage', 'registry' => false),
			),
			'fallback_menus' => array('without_bvm' => 'none'),
			'notice' => array('owner_patterns' => array('VMS Meta Ads Builder', 'VMS Meta Ads', 'Backstage Venue Manager or legacy VMS'), 'present' => '', 'absent' => 'Backstage Venue Manager or legacy VMS module system is unavailable'),
			'post_types' => array('vms_event_plan', 'vms_venue'),
			'meta' => array('_vms_event_plan_status', '_vms_tec_event_id', '_vms_venue_id', '_vms_ticket_url'),
			'options' => array('vms_ma_settings', 'vms_ma_db_version'),
			'tables' => array('vms_meta_ads_builds', 'vms_meta_ads_templates', 'vms_meta_ads_tiers', 'vms_meta_ads_audit'),
			'rest_namespaces' => array('vms-ma/v1'), 'ajax_actions' => array('vms_api_copy_bundle', 'vms_api_diag_panel_html'),
			'cron_hooks' => array('vms_ma_budget_sync_cron', 'vms_api_attempts_prune_daily'),
		)),
		'vms-ops-console-premium' => $base(array(
			'name' => 'VMS Ops Console Premium', 'version' => '0.1.68',
			'entry' => 'vms-ops-console-premium/vms-ops-console-premium.php',
			'dependency' => 'BVM optional; guarded enrichment',
			'companions' => array('required' => array(), 'optional' => array('woocommerce', 'event-tickets', 'vms-season-passes')),
			'marker' => array('constant' => 'VMS_OPS_CONSOLE_VERSION', 'value' => '0.1.68'),
			'capabilities' => array(
				$capability('meta-contract', 'feature path', 'bvmgr_meta_key', 'vms_meta_key', 'backstage-venue-manager', 'canonical-first guarded fallback', 'Ops retains standalone operation'),
				$capability('addon-manifest-history', 'registration', '', 'vms_addons_manifest_entries', 'backstage-venue-manager', 'callback may attach; hook is not emitted', 'historical dead path is not accepted as BVM support'),
			),
			'hooks' => array(array('name' => 'vms_addons_manifest_entries', 'kind' => 'filter', 'emission' => 'historical-dead', 'callback' => 'vms_ops_filter_addons_manifest_entries')),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-ops-console-members', 'capability' => 'vms_ops_manage_members_admin', 'registry' => false)),
			'fallback_menus' => array('without_bvm' => 'standalone ops pages remain available'),
			'notice' => array('owner_patterns' => array('VMS Ops Console', 'VMS Ops'), 'present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_venue'),
			'meta' => array('_vms_event_plan_start_datetime', '_vms_venue_id', '_vms_staff_id', '_vms_linked_user_id'),
			'options' => array('vms_ops_db_version'),
			'tables' => array('vms_ops_members', 'vms_ops_visits', 'vms_ops_presence', 'vms_ops_pc_scan_log'),
			'rest_namespaces' => array('vms-ops/v1'), 'cron_hooks' => array('vms_ops_presence_expire_event'),
		)),
		'vms-season-passes' => $base(array(
			'name' => 'VMS Season Passes', 'version' => '0.1.0',
			'entry' => 'vms-season-passes/vms-season-passes.php',
			'dependency' => 'BVM required; WooCommerce and Ops optional',
			'companions' => array('required' => array(), 'optional' => array('woocommerce', 'vms-ops-console-premium')),
			'marker' => array('constant' => 'VMS_SEASON_PASSES_VERSION', 'value' => '0.1.0'),
			'capabilities' => array(
				$capability('core-identity', 'bootstrap', 'BVMGR_VERSION', 'VMS_VERSION', 'backstage-venue-manager', 'canonical-first version resolver', 'runtime boots for BVM 1.3.0'),
				$capability('module-registration', 'registration', 'bvmgr_register_module', 'vms_register_module', 'backstage-venue-manager', 'canonical-first resolver', 'season_passes module registered'),
				$capability('admin-registry', 'registration', 'bvmgr_register_admin_page', 'vms_register_admin_page', 'backstage-venue-manager', 'canonical-first resolver; no fallback without core', 'canonical registry entry and one physical menu'),
				$capability('event-plan-resolution', 'feature path', 'bvmgr_get_event_plan_for_tec_event', 'vms_get_event_plan_for_tec_event', 'the-events-calendar', 'canonical-first resolver', 'TEC scans resolve through canonical provider'),
				$capability('normalization', 'feature path', 'bvmgr_admission_normalize_email', 'vms_admission_normalize_email', 'backstage-venue-manager', 'canonical-first with local fallback', 'scanner inputs normalize safely'),
			),
			'hooks' => array(array('name' => 'vms_admin_register_pages', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => 'vms_season_passes_register_admin_page_metadata')),
			'hook_callbacks' => array('vms_admin_register_pages' => 'vms_season_passes_register_admin_page_metadata'),
			'menus' => array(array('parent' => 'vms-dashboard', 'slug' => 'vms-season-passes', 'capability' => 'vms_season_pass_manage', 'registry' => true, 'callback_method' => 'vms_season_passes_render_admin_page')),
			'fallback_menus' => array('without_bvm' => 'none'),
			'notice' => array('owner_patterns' => array('VMS Season Passes', 'Activate Venue Management System first'), 'present' => '', 'absent' => 'Activate Venue Management System first'),
			'post_types' => array('vms_event_plan'), 'meta' => array('_vms_event_plan_id'),
			'options' => array('vms_season_passes_db_version'),
			'tables' => array('vms_season_pass_types', 'vms_season_passholders', 'vms_season_pass_checkins'),
		)),
		'vms-sponsorships' => $base(array(
			'name' => 'VMS Sponsorships', 'version' => '0.1.28',
			'entry' => 'vms-sponsorships/vms-sponsorships.php',
			'dependency' => 'local candidate; BVM optional with canonical registry preferred',
			'companions' => array('required' => array(), 'optional' => array('the-events-calendar')),
			'marker' => array('constant' => 'VMS_SPONSORSHIPS_VERSION', 'value' => '0.1.28'),
			'capabilities' => array(
				$capability('admin-registry', 'registration', 'bvmgr_register_admin_page', 'vms_register_admin_page', 'backstage-venue-manager', 'canonical-first resolver; standalone fallback only when unavailable', 'seven canonical registry entries without duplicate fallback rows'),
				$capability('event-commerce-placement', 'feature path', 'bvmgr_event_details_commerce_hook', 'vms_event_details_commerce_hook', 'backstage-venue-manager', 'canonical-first with TEC hook fallback', 'shortcode placement remains available'),
			),
			'hooks' => array(
				array('name' => 'vms_admin_register_pages', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => array('VMS_Sponsorships_Admin', 'register_vms_admin_pages')),
				array('name' => 'vms_event_plan_after_modules', 'kind' => 'action', 'emission' => 'historical-dead', 'callback' => array('VMS_Sponsorships_Event_Plans', 'render_vms_event_plan_card')),
			),
			'hook_callbacks' => array('vms_admin_register_pages' => array('VMS_Sponsorships_Admin', 'register_vms_admin_pages')),
			'menus' => array(
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_dashboard'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-applications', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_applications'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-assignments', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_assignments'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-packages', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_packages'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-assets', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_assets'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-visibility', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_visibility_stats'),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-sponsorships-settings', 'capability' => 'manage_options', 'registry' => true, 'callback_method' => 'render_settings'),
			),
			'fallback_menus' => array('top_without_bvm' => 'vms-sponsorships'),
			'notice' => array('owner_patterns' => array('VMS Sponsorships', 'Sponsorships'), 'present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_event', 'tribe_events'),
			'meta' => array('_vms_event_date', '_vms_expected_attendance', '_vms_sponsorship_price_multiplier', '_vms_sponsorship_value_tier'),
			'options' => array('vms_sponsorships_version', 'vms_sponsorships_seeded_defaults'),
			'tables' => array('vms_sponsorship_applications', 'vms_sponsorship_packages', 'vms_sponsorship_assignments', 'vms_sponsor_assets'),
		)),
		'vmsx-checkout-policies' => $base(array(
			'name' => 'VMS Checkout Policies', 'version' => '0.1.8',
			'entry' => 'vmsx-checkout-policies/vmsx-checkout-policies.php',
			'dependency' => 'WooCommerce required; BVM settings integration optional',
			'companions' => array('required' => array('woocommerce'), 'optional' => array()),
			'marker' => array('constant' => 'VMSX_CHECKOUT_POLICIES_VERSION', 'value' => '0.1.8'),
			'capabilities' => array(
				$capability('core-identity', 'bootstrap', 'BVMGR_VERSION', 'VMS_VERSION', 'backstage-venue-manager', 'canonical-first resolver', 'BVM settings location selected'),
				$capability('settings-renderer', 'registration', 'bvmgr_render_settings_page', 'vms_render_settings_page', 'backstage-venue-manager', 'canonical-first detection', 'no Woo fallback menu while BVM is available'),
				$capability('ticket-meta', 'feature path', 'bvmgr_ticketing_v2_meta_get', 'vms_ticketing_v2_meta_get', 'backstage-venue-manager', 'canonical-first with raw-key fallback', 'event ticket products retain policy detection'),
			),
			'fallback_menus' => array('with_woocommerce_without_bvm' => 'vmsx-checkout-policies', 'without_woocommerce' => 'none'),
			'notice' => array('owner_patterns' => array('Checkout Policies', 'Checkout policy'), 'present' => '', 'absent' => ''),
			'post_types' => array('product'), 'meta' => array('_vms_event_plan_id', '_vms_product_role'),
			'options' => array('vmsx_checkout_policies_settings'),
		)),
		'vmsx-weather-risk' => $base(array(
			'name' => 'VMSX Weather Risk', 'version' => '0.1.12',
			'entry' => 'vmsx-weather-risk/vmsx-weather-risk.php',
			'dependency' => 'BVM required; Data Tools optional',
			'companions' => array('required' => array(), 'optional' => array('vms-data-tools')),
			'marker' => array('constant' => 'VMSX_WR_VERSION', 'value' => '0.1.12'),
			'capabilities' => array(
				$capability('core-path', 'bootstrap', 'BVMGR_PLUGIN_PATH', 'VMS_PLUGIN_PATH', 'backstage-venue-manager', 'canonical-first constant resolver', 'canonical source path recognized'),
				$capability('core-version', 'bootstrap', 'BVMGR_VERSION', 'VMS_VERSION', 'backstage-venue-manager', 'canonical-first version resolver', 'runtime ready for BVM 1.3.0'),
				$capability('module-registration', 'registration', 'bvmgr_register_module', 'vms_register_module', 'backstage-venue-manager', 'canonical-first resolver', 'weather module registered'),
				$capability('admin-shell', 'feature path', 'bvmgr_admin_ui_render_shell', 'vms_admin_ui_render_shell', 'backstage-venue-manager', 'canonical-first with local wrapper fallback', 'both admin pages render'),
				$capability('ticket-labor', 'feature path', 'bvmgr_event_profitability_get_labor_cost_cents', 'vms_event_profitability_get_labor_cost_cents', 'backstage-venue-manager', 'canonical-first with zero fallback', 'risk exposure remains safe'),
				$capability('data-tools-enrichment', 'feature path', '', 'vms_dt_reporting_ticket_pace_rows', 'vms-data-tools', 'all-provider function guard', 'base Weather runtime survives Data Tools absence'),
			),
			'hooks' => array(
				array('name' => 'vms_register_docs_sources', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => array('VMSX_Weather_Risk', 'register_docs_source')),
				array('name' => 'vms_admin_ui_nav_cluster_items', 'kind' => 'filter', 'emission' => 'bvm-emitted', 'callback' => array('VMSX_Weather_Risk_Admin_Menu', 'register_compact_nav_items')),
				array('name' => 'vms_admin_ui_active_cluster', 'kind' => 'filter', 'emission' => 'bvm-emitted', 'callback' => array('VMSX_Weather_Risk_Admin_Menu', 'filter_active_cluster')),
				array('name' => 'vms_admin_ui_shell_pages', 'kind' => 'filter', 'emission' => 'bvm-emitted', 'callback' => array('VMSX_Weather_Risk_Admin_Menu', 'register_shell_pages')),
				array('name' => 'vms_event_plan_advanced_controls_after_intro', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => array('VMSX_Weather_Risk_Metabox_Event_Plan', 'render_card')),
				array('name' => 'vms_event_plan_saved', 'kind' => 'action', 'emission' => 'bvm-emitted', 'callback' => array('VMSX_Weather_Risk_Scheduler', 'invalidate_event_snapshot')),
				array('name' => 'vms_addons_manifest_entries', 'kind' => 'filter', 'emission' => 'historical-dead', 'callback' => array('VMSX_Weather_Risk', 'filter_manifest_entries')),
			),
			'hook_callbacks' => array(
				'vms_register_docs_sources' => array('VMSX_Weather_Risk', 'register_docs_source'),
				'vms_admin_ui_nav_cluster_items' => array('VMSX_Weather_Risk_Admin_Menu', 'register_compact_nav_items'),
				'vms_admin_ui_active_cluster' => array('VMSX_Weather_Risk_Admin_Menu', 'filter_active_cluster'),
				'vms_admin_ui_shell_pages' => array('VMSX_Weather_Risk_Admin_Menu', 'register_shell_pages'),
			),
			'menus' => array(
				array('parent' => 'vms-dashboard', 'slug' => 'vms-weather-risk', 'capability' => 'manage_options', 'registry' => false),
				array('parent' => 'vms-dashboard', 'slug' => 'vms-weather-risk-settings', 'capability' => 'manage_options', 'registry' => false),
			),
			'fallback_menus' => array('without_bvm' => 'none'),
			'notice' => array('owner_patterns' => array('Show Risk Advisor', 'Weather Risk', 'requires the VMS core plugin'), 'present' => '', 'absent' => 'requires the VMS core plugin'),
			'post_types' => array('vms_event_plan', 'vms_venue'),
			'meta' => array('_vms_event_date', '_vms_start_time', '_vms_end_time', '_vms_venue_id', '_vms_ticket_stats_v1'),
			'options' => array('vmsx_weather_risk_settings', 'vmsx_weather_risk_log'),
			'ajax_actions' => array('vmsx_weather_risk_refresh'), 'cron_hooks' => array('vmsx_weather_risk_refresh_cron'),
		)),
		'drm-events-bridge' => $base(array(
			'name' => 'DRM Events Bridge', 'version' => '0.2.2',
			'entry' => 'drm-events-bridge/drm-events-bridge.php',
			'dependency' => 'Router-authoritative public adapter; BVM enrichment optional',
			'companions' => array('required' => array('drm-calendar-intake', 'drm-event-router'), 'optional' => array()),
			'marker' => array('constant' => 'DRM_EVENTS_BRIDGE_VERSION', 'value' => '0.2.2'),
			'capabilities' => array(
				$capability('router-provider', 'bootstrap', 'drm_event_router_get_public_events', '', 'drm-event-router', 'contract-version and callable guards', 'Router v2 payload is authoritative'),
				$capability('bvm-enrichment', 'feature path', 'bvmgr_meta_key', 'vms_meta_key', 'backstage-venue-manager', 'optional function guard', 'Bridge remains operational without BVM'),
			),
			'hooks' => array(array('name' => 'dalene_richelle_site_public_event_provider', 'kind' => 'filter', 'emission' => 'external-emitted', 'callback' => 'drm_events_bridge_local_public_event_provider')),
			'hook_callbacks' => array('dalene_richelle_site_public_event_provider' => 'drm_events_bridge_local_public_event_provider'),
			'menus' => array(array('parent' => 'options-general.php', 'slug' => 'drm-events-bridge', 'capability' => 'manage_options', 'registry' => false)),
			'fallback_menus' => array('without_bvm' => 'same WordPress Settings page'),
			'notice' => array('owner_patterns' => array('DRM Events Bridge', 'Bridge requires', 'Activate BVM'), 'present' => '', 'absent' => ''),
			'post_types' => array('vms_event_plan', 'vms_vendor'), 'meta' => array('_vms_event_plan_status', '_drm_publish_to_dalene_site'),
			'options' => array('drm_events_bridge_vendor_map'), 'rest_namespaces' => array('drm-events/v1'),
		)),
	),
	'blocked' => array(),
	'retired' => array(
		'vms-safety-pro' => array(
			'name' => 'VMS Safety Toolkit Pro', 'version' => '0.1.0',
			'status' => 'RETIRED / UNSUPPORTED — excluded from supported runtime and coexistence scenarios',
			'historical_evidence' => array('vms_safety_admin_url', 'vms_safety_audit_log', 'vms_safety_manage_capability', 'VMS_CAP_SAFETY_TEMPLATES', 'vms_doc'),
		),
	),
	'indirect' => array(
		'drm-event-router' => array('version' => '0.1.3', 'reason' => 'Current installed authoritative Bridge provider; public contract v2; no direct BVM runtime dependency.'),
		'backstage-calendar-feeds' => array('reason' => 'Consumes Calendar Intake provider contracts; no direct BVM runtime contract.'),
		'event-venue-map-modal' => array('reason' => 'TEC presentation integration only; no direct BVM runtime contract.'),
	),
	'hook_emission' => array(
		'bvm_emitted' => array('vms_admin_register_pages', 'vms_register_docs_sources', 'vms_register_tours', 'vms_admin_ui_nav_cluster_items', 'vms_admin_ui_active_cluster', 'vms_admin_ui_shell_pages', 'vms_event_plan_advanced_controls_after_intro', 'vms_event_plan_saved'),
		'historical_dead' => array('vms_addons_manifest_entries', 'vms_event_plan_after_modules'),
	),
);

return $contracts;
