<?php

/**
 * VMS Keys + Identifiers Registry (Authoritative)
 * Keys-only and naming-only. Do not store secrets or live values here.
 */

if (!defined('ABSPATH')) {
  exit;
}

function vms_keys_map_registry()
{
  return array(

    // =========================
    // CANONICAL IDENTIFIERS
    // =========================
    'canonical_identifiers' => array(
      'title' => 'CANONICAL IDENTIFIERS (CODE-LEVEL, AUTHORITATIVE NAMING)',
      'lines' => array(
        'Purpose: Answer “What do we call this in code?” without searching.',
        'Rule: Naming only (variables, params, IDs, keys). No runtime values.',

        '',
        'CPTs (authoritative constants / registration functions):',
        '  Vendor CPT constant: VMS_VENDOR_CPT = vms_vendor',
        '  Venue CPT registration function: vms_register_venue_cpt()',
        '  Venue CPT constant: VMS_VENUE_CPT (vms_venue)',
        '  Event Plan CPT constant: VMS_CPT_EVENT_PLAN = vms_event_plan',
        '  Continuity Binder option key constant: VMS_CONTINUITY_BINDER_OPTION = vms_continuity_binder_v1',

        '',
        'Entity: Venue',
        '  Canonical variable: $venue_id',
        '  Canonical ID type: int (WordPress post ID)',
        '  CPT: vms_venue',
        '  Common representations:',
        '    - $venue_id (PHP variable)',
        '    - venue_id (URL param / request arg name)',
        '    - _vms_current_venue_id (user_meta key for persisted selection)',
        '    - _vms_schedule_scope (user_meta key: Schedule scope; values: venue|all)',
        '    - _vms_include_drafts (user_meta key: Include Draft/Ready what-if across Schedule/Event Plans/Dashboard; values: 0|1)',
        '    - _vms_dash_scope (user_meta key: dashboard scope; values: venue|all)',
        '    - _vms_dash_venue_id (user_meta key: dashboard selected venue_id; scope=venue)',
        '    - Arrays keyed by venue_id (e.g., options payloads keyed by venue_id)',
        '  Notes: Venue ID should always mean the WP post ID of the venue CPT.',

        '',
        'Entity: Vendor',
        '  Canonical variable: $vendor_id',
        '  Canonical ID type: int (WordPress post ID)',
        '  CPT: VMS_VENDOR_CPT (vms_vendor)',
        '  Common representations:',
        '    - $vendor_id (PHP variable)',
        '    - vendor_id (request arg name when applicable)',
        '    - _vms_vendor_id (user_meta key on WP user record: PRIMARY/default vendor post ID for portal convenience)',
        '    - _vms_vendor_user_id (post_meta on vendor: PRIMARY contact WP user ID for vendor convenience)',
        '    - {$wpdb->prefix}vms_vendor_user_links (DB table: many-to-many vendor↔user mapping)',
        '      - vendor_id, user_id, user_role, link_status, is_primary, created_at/by, updated_at/by',
        '  Notes: Vendor ID should always mean the WP post ID of the vendor CPT. The authoritative vendor↔user links live in the DB table; the meta keys above are convenience pointers.',

        '',
        'Entity: Event Plan',
        '  Canonical variable: $event_plan_id (or $plan_id if clearly scoped)',
        '  Canonical ID type: int (WordPress post ID)',
        '  CPT: vms_event_plan',
        '  Common representations:',
        '    - $event_plan_id (PHP variable)',
        '    - $plan_id (allowed only when file/function scope makes it unambiguous)',
        '    - post_id (generic request arg in WP admin contexts)',
        '  Notes: Prefer $event_plan_id in new code for clarity.',

        '',
        'Entity: Headliner Vendor on Event Plan',
        '  Canonical variable: $vendor_id (scoped as headliner)',
        '  Storage key: _vms_band_vendor_id (post_meta on vms_event_plan)',
        '  Notes: When ambiguity exists, use $headliner_vendor_id in local scope.',
      ),
    ),

    // =========================
    // SECTION 08 KEYS MAP
    // =========================
    'section_08_header' => array(
      'title' => 'SECTION 08 — STORAGE + KEYS MAP (AUTHORITATIVE, CRITICAL KEYS ONLY)',
      'lines' => array(
        'Rule: This section lists WHERE data lives + the canonical key names.',
        'Do NOT duplicate full schemas here; point to registry files for full definitions.',
      ),
    ),

    'vendor_schema' => array(
      'title' => 'A) Vendor schema',
      'lines' => array(
        'Storage: WordPress CPT vms_vendor (display_name stored in post_title; other fields stored in post_meta per vms_vendor_schema()).',
        'Authoritative registry file: vms/includes/core/registry/meta-keys.php',
        'Storage mapping source: vms/includes/core/registry/vendor-schema.php',
        'Critical keys (only):',
        '_vms_vendor_primary_email = “Primary Contact Email” (schema field: primary_email)',
        '_vms_vendor_primary_phone = “Primary Phone” (schema field: primary_phone)',
        '_vms_vendor_email = “Vendor Email” (schema field uses vms_meta_key(\'vendor\',\'email\'))',
        '_vms_vendor_phone = “Vendor Phone” (schema field uses vms_meta_key(\'vendor\',\'phone\'))',
        '_vms_vendor_default_comp_by_venue = “Vendor Event Plan default overrides keyed by venue_id” (schema key: vms_meta_key(\'vendor\',\'default_comp_by_venue\'))',
        '_vms_vendor_default_comp_by_venue_dow = “Vendor Event Plan default overrides keyed by venue_id + day-of-week (0..6)” (schema key: vms_meta_key(\'vendor\',\'default_comp_by_venue_dow\'))',
        '_vms_default_attendance_bonus_mode = “Vendor default attendance-bonus mode (step|continuous)” (post_meta on vms_vendor)',
        '_vms_default_attendance_bonus_start_count = “Vendor default attendance-bonus starting count” (post_meta on vms_vendor)',
        '_vms_default_attendance_bonus_step_size = “Vendor default attendance-bonus step size” (post_meta on vms_vendor)',
        '_vms_default_attendance_bonus_step_bonus = “Vendor default attendance-bonus bonus per step” (post_meta on vms_vendor)',
        '_vms_default_attendance_bonus_per_ticket_rate = “Vendor default attendance-bonus rate per ticket” (post_meta on vms_vendor)',
        '_vms_default_attendance_bonus_max_bonus = “Vendor default attendance-bonus max bonus cap” (post_meta on vms_vendor)',
        '_vms_default_comp_package_id = “Vendor default Comp Package template ID used as a reusable booking baseline” (post_meta on vms_vendor)',
        '_vms_vendor_user_id = “Linked WP user ID for portal access” (vendor post_meta; VMS_VENDOR_USER_META_KEY)',
        '_vms_vendor_id = “Linked vendor post ID on WP user record” (user_meta; one-to-one link)',
      ),
    ),

    'vendor_applications' => array(
      'title' => 'A.1) Vendor applications',
      'lines' => array(
        'Storage: WordPress CPT vms_vendor_app (status stored in _vms_app_status post_meta).',
        'Critical keys (only):',
        '_vms_app_submitted_user_id = “Logged-in WP user who submitted this vendor application” (post_meta on vms_vendor_app; registry key: vms_meta_key(\'vendor_application\',\'submitted_user_id\'))',
        '_vms_vendor_id = “Approved vendor post created or linked from this application” (post_meta on vms_vendor_app)',
      ),
    ),

    'season_dates' => array(
      'title' => 'B) Season Dates (per venue)',
      'lines' => array(
        'Rules storage location: wp_options option vms_season_rules_v1 (array keyed by venue_id → rules[]).',
        'Active payload storage location: wp_options option vms_season_active_dates_v1 (array keyed by venue_id → payload).',
        'Critical keys (only):',
        'vms_season_rules_v1 = “season rules array”',
        'vms_season_active_dates_v1 = “generated dates payload”',
        'Engine file: vms/includes/schedule/season-dates.php',
        'Admin file: vms/includes/admin/season-dates.php',
      ),
    ),

    'event_plans' => array(
      'title' => 'C) Event plans / schedule (if applicable)',
      'lines' => array(
        'Storage: WordPress CPT vms_event_plan',
        'Critical keys/slugs (only):',
        '_vms_event_plan_status = “Internal status: draft/ready/published” (post_meta on vms_event_plan)',
        '_vms_cancel_policy = “Cancellation policy key selected at cancel time” (post_meta on vms_event_plan)',
        '_vms_cancel_reason_code = “Cancellation reason code selected by operator” (post_meta on vms_event_plan)',
        '_vms_cancel_reason_note = “Optional operator cancellation note” (post_meta on vms_event_plan)',
        '_vms_cancelled_at_gmt = “Cancellation timestamp (GMT)” (post_meta on vms_event_plan)',
        '_vms_cancelled_by_user_id = “WP user who initiated cancellation” (post_meta on vms_event_plan)',
        '_vms_cancel_job_id = “Cancellation orchestration job id” (post_meta on vms_event_plan)',
        '_vms_cancel_job_state = “Cancellation orchestration state” (post_meta on vms_event_plan)',
        '_vms_cancel_job_summary = “Cancellation orchestration summary payload” (post_meta on vms_event_plan)',
        '_vms_cancel_requires_operator_review = “Cancellation requires operator review before execution (1/0)” (post_meta on vms_event_plan)',
        '_vms_rescheduled_from_plan_id = “Source cancelled Event Plan ID when this plan was created as a reschedule draft” (post_meta on vms_event_plan)',
        '_vms_rescheduled_to_plan_ids = “Replacement Event Plan IDs created from this cancelled plan” (post_meta on vms_event_plan)',
        '_vms_band_vendor_id = “Primary vendor ID on event plan” (post_meta on vms_event_plan)',
        '_vms_secondary_vendor_ids = “Secondary vendor IDs array” (post_meta on vms_event_plan)',
        '_vms_secondary_vendor_type = “Secondary vendor type” (post_meta on vms_event_plan)',
        '_vms_tec_event_id = “Linked TEC event ID on event plan” (post_meta on vms_event_plan)',
        '_vms_tec_event_url = “Linked TEC event URL (permalink) on event plan” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_attachment_id = “Headliner promo video attachment ID for this event plan” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_hidden = “Headliner promo video public visibility flag (1/0)” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_uploaded_at_gmt = “Headliner promo video uploaded timestamp (GMT)” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_uploaded_by = “WP user who uploaded the headliner promo video” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_source_type = “Active public promo source type: attachment|external” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_external_url = “Active public promo external video URL” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_pending_attachment_id = “Vendor-submitted promo clip waiting for operator review” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_pending_uploaded_at_gmt = “Vendor-submitted promo clip timestamp (GMT)” (post_meta on vms_event_plan)',
        '_vms_headliner_promo_video_pending_uploaded_by = “WP user who submitted the pending promo clip” (post_meta on vms_event_plan)',
        '_vms_ticket_product_ids_v1 = “Cached Woo ticket product IDs detected for linked TEC event” (post_meta on vms_event_plan)',
        '_vms_ticket_stats_v1 = “Cached ticket stats payload (sold, revenue, provider, timestamp)” (post_meta on vms_event_plan)',
        '_vms_ticketing_config_v2 = “Ticketing v2 config (GA + entitlements + rules)” (post_meta on vms_event_plan)',
        '_vms_ticketing_sync_v2 = “Ticketing v2 last sync payload (preview/commit results)” (post_meta on vms_event_plan)',
	        '_vms_ticketing_stats_v2 = “Ticketing v2 cached stats (sold, revenue) for GA + entitlements” (post_meta on vms_event_plan)',
	        '_vms_ticketing_migration_snapshot_v1 = “Ticketing v2 migration snapshot from legacy tiers (one-time)” (post_meta on vms_event_plan)',
	        '_vms_social_do_not_post = “Per-event block toggle for social posting (1/0)” (post_meta on vms_event_plan)',
	        '_vms_social_platform_overrides = “Per-event platform enabled flags map (facebook/linkedin/x)” (post_meta on vms_event_plan)',
	        '_vms_social_template_overrides = “Per-event template id overrides keyed by platform” (post_meta on vms_event_plan)',
	        '_vms_social_unpublished_after_post = “Flag set when event is Draft after previously posted social queue item(s)” (post_meta on vms_event_plan)',
	        '_vms_event_plan_id = “Link marker: owning Event Plan ID on Woo products” (post_meta on product)',
        '_vms_tec_event_id = “Link marker: linked TEC event ID on Woo products” (post_meta on product)',
        '_vms_product_role = “Link marker: product role (ga_ticket|entitlement|legacy_ticket|other)” (post_meta on product)',
        '_vms_ticketing_entitlement_id = “Link marker: entitlement id on Woo products” (post_meta on product)',
        '_vms_ticketing_marker_version = “Link marker: marker schema version” (post_meta on product)',
        '_vms_calendar_unpublished_suppress = “Suppress only calendar-unpublished integrity warnings for this plan” (post_meta on vms_event_plan)',
        '_vms_comp_structure = “Comp structure key (e.g., flat_fee)” (post_meta on vms_event_plan)',
        '_vms_flat_fee_amount = “Flat fee amount for exports/payables” (post_meta on vms_event_plan)',
        '_vms_door_split_percent = “Door split percentage for exports/payables” (post_meta on vms_event_plan)',
        '_vms_attendance_bonus_mode = “Attendance bonus mode (step|continuous)” (post_meta on vms_event_plan)',
        '_vms_attendance_bonus_start_count = “Attendance bonus threshold start count” (post_meta on vms_event_plan)',
        '_vms_attendance_bonus_step_size = “Attendance bonus step size” (post_meta on vms_event_plan)',
        '_vms_attendance_bonus_step_bonus = “Attendance bonus amount earned per step” (post_meta on vms_event_plan)',
        '_vms_attendance_bonus_per_ticket_rate = “Attendance bonus rate earned per ticket above threshold” (post_meta on vms_event_plan)',
        '_vms_attendance_bonus_max_bonus = “Attendance bonus max bonus cap” (post_meta on vms_event_plan)',
        '_vms_deposit_amount = “Event-level vendor deposit amount” (post_meta on vms_event_plan)',
        '_vms_deposit_status = “Event-level vendor deposit status (not_required|unpaid|paid|waived|refunded)” (post_meta on vms_event_plan)',
        '_vms_deposit_treatment = “Event-level vendor deposit treatment (creditable|refundable|nonrefundable)” (post_meta on vms_event_plan)',
        '_vms_deposit_due_date = “Event-level vendor deposit due date (Y-m-d)” (post_meta on vms_event_plan)',
        '_vms_deposit_paid_date = “Event-level vendor deposit paid date (Y-m-d)” (post_meta on vms_event_plan)',
        '_vms_deposit_notes = “Event-level vendor deposit notes for agreement/pay context” (post_meta on vms_event_plan)',
        '_vms_final_payment_timing = “Expected final vendor payment timing (not_set|in_advance|day_of_event|days_after|fixed_date|custom)” (post_meta on vms_event_plan)',
        '_vms_final_payment_days_after = “Expected final vendor payment days after event” (post_meta on vms_event_plan)',
        '_vms_final_payment_date = “Expected final vendor payment fixed date (Y-m-d)” (post_meta on vms_event_plan)',
        '_vms_final_payment_custom_text = “Expected final vendor payment custom text” (post_meta on vms_event_plan)',
        '_vms_final_payment_method = “Expected final vendor payment method including ach_direct_deposit” (post_meta on vms_event_plan)',
        '_vms_final_payment_method_other = “Expected final vendor payment custom method label” (post_meta on vms_event_plan)',
        '_vms_import_event_key = “CSV upsert identifier for Event Plan imports” (post_meta on vms_event_plan)',
        '_vms_comp_selected_option = “Last selected compensation option tile (default:<structure>|package:<id>|holiday:<name>) for UI persistence” (post_meta on vms_event_plan)',
        '_vms_pay_override_ack = “Draft pay differs from defaults acknowledged (1/0)” (post_meta on vms_event_plan)',
        '_vms_pay_override_ack_ts = “Timestamp of override acknowledgment” (post_meta on vms_event_plan)',
        '_vms_pay_override_ack_user_id = “WP user ID who acknowledged override” (post_meta on vms_event_plan)',
        '_vms_pay_override_ack_default_snapshot = “Defaults snapshot at acknowledgment” (post_meta on vms_event_plan)',
        '_vms_pay_override_ack_actual_snapshot = “Draft pay snapshot at acknowledgment” (post_meta on vms_event_plan)',
        '_vms_pay_default_source = “Computed default source (holiday|venue) for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_structure = “Computed default structure for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_flat_fee_amount = “Computed default flat fee for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_door_split_percent = “Computed default door split for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_attendance_bonus_mode = “Computed default attendance-bonus mode for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_attendance_bonus_start_count = “Computed default attendance-bonus start count for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_attendance_bonus_step_size = “Computed default attendance-bonus step size for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_attendance_bonus_step_bonus = “Computed default attendance-bonus step bonus for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_attendance_bonus_per_ticket_rate = “Computed default attendance-bonus per-ticket rate for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_attendance_bonus_max_bonus = “Computed default attendance-bonus max bonus cap for venue/date” (post_meta on vms_event_plan)',
        '_vms_pay_default_holiday_name = “Holiday name when source is holiday” (post_meta on vms_event_plan)',
        '_vms_low_guarantee_ack = “Lower-than-max guaranteed selection acknowledged (1/0)” (post_meta on vms_event_plan)',
        '_vms_low_guarantee_ack_ts = “Timestamp of low-guarantee acknowledgment” (post_meta on vms_event_plan)',
        '_vms_low_guarantee_ack_user_id = “WP user ID who acknowledged low-guarantee selection” (post_meta on vms_event_plan)',
        '_vms_low_guarantee_ack_snapshot = “Snapshot at low-guarantee acknowledgment” (post_meta on vms_event_plan)',
      ),
    ),

    'settings' => array(
      'title' => 'D) Settings',
      'lines' => array(
        'Storage: wp_options',
        'Option keys (critical only):',
        'vms_db_schema_version = “DB schema/migration version marker”',
        'vms_settings = “Settings array (stored as option)”',
	        'sch_hide_past_default = “Hide past dates by default (Schedule list view)” (key inside vms_settings)',
	        'ticket_ui_show_availability = “Legacy show/hide available/remaining counts on front ticket rows” (key inside vms_settings)',
	        'ticket_ui_availability_display = “Total ticket availability display mode: always|low|hide” (key inside vms_settings)',
	        'ticket_ui_availability_low_threshold = “Threshold for low-only total ticket availability display” (key inside vms_settings)',
	        'ticket_ui_sale_availability_display = “Capped sale quantity display mode: when_capped|low|hide” (key inside vms_settings)',
	        'ticket_ui_sale_availability_low_threshold = “Threshold for low-only capped sale quantity display” (key inside vms_settings)',
	        'help_mode = “Admin help mode: off|basic|guided” (key inside vms_settings)',
	        'vms_admission_db_version = “Guest List/Admission DB schema version marker”',
	        'vms_ticket_mutation_audit_db_schema_version = “Ticket mutation audit DB schema version marker”',
	        '{$wpdb->prefix}vms_ticket_mutation_audit = “Ticket mutation audit log table for Event Plan mapping/config writes”',
	        'vms_ticket_inventory_audit_db_schema_version = “Ticket inventory audit DB schema version marker”',
	        '{$wpdb->prefix}vms_ticket_inventory_audit = “Ticket inventory audit log table for TEC/Woo inventory and capacity writes”',
	        'vms_admission_max_party_size = “Max allowed party size per comp entry” (key inside vms_settings)',
	        'vms_admission_allow_uncheckin = “Allow undo check-in flow” (key inside vms_settings)',
	        'vms_admission_allow_uncheckin_for_door = “Allow door-staff undo check-in” (key inside vms_settings)',
	        'vms_admission_door_show_phone = “Door UI may show unmasked phone” (key inside vms_settings)',
	        'vms_pass_claim_token = “Front-end pass claim route query var (rewrite tag)”',
			'vms_ticketing_templates_v1 = “Ticketing v2 templates library” (constant: VMS_OPT_TICKETING_TEMPLATES_V1)',
			'vms_ticketing_default_template_v1 = “Ticketing v2 default template id” (constant: VMS_OPT_TICKETING_DEFAULT_TEMPLATE_V1)',
	        'vms_social_settings_v1 = “Social sharing global settings (enabled/kill_switch/utm/retry)” (constant: VMS_OPT_SOCIAL_SETTINGS_V1)',
	        'vms_social_db_schema_version = “Social module table schema marker” (constant: VMS_OPT_SOCIAL_DB_SCHEMA_VERSION)',
	      ),
	    ),

    'holidays' => array(
      'title' => 'E) Holidays (per venue + date)',
      'lines' => array(
        'Storage: wp_options',
        'Option key:',
        'vms_holidays = “Venue-scoped holiday map”',
      ),
    ),

    'continuity_binder' => array(
      'title' => 'F) Continuity Binder (ops documentation)',
      'lines' => array(
        'Storage: wp_options',
        'Option key:',
        'vms_continuity_binder_v1 = “Continuity Binder content storage” (constant: VMS_CONTINUITY_BINDER_OPTION)',
      ),
    ),

    'due_dates' => array(
      'title' => 'G) Due Dates (Dashboard)',
      'lines' => array(
        'Storage: wp_options',
        'Option keys:',
        'vms_due_payees_v1 = “Due Dates payees map” (keyed by payee_id)',
        'vms_due_obligations_v1 = “Due Dates obligations map” (keyed by obligation_id)',
        'vms_due_log_v1 = “Due Dates completion log (append-only)”',
        '',
        'Payee object fields (naming only; stored inside vms_due_payees_v1):',
        '  id (string; payee_[uuid])',
        '  name (string)',
        '  notes (string)',
        '  identifiers[] (array of {label, value})',
        '  is_active (int 1|0; archived when 0)',
        '',
        'Obligation object fields (naming only; stored inside vms_due_obligations_v1):',
        '  id (string; ob_[uuid])',
        '  title (string)',
        '  payee_id (string; foreign key → payee.id)',
        '  payee_required (int 1|0; 1 default; when 0, blank payee_id is allowed)',
        '  cadence (string; monthly|quarterly|annual|one_time)',
        '  day (int; day-of-month for monthly/quarterly/annual)',
        '  month (int; month-of-year for annual; or month within cadence)',
        '  quarter_month (int 1..3; month index within the quarter for quarterly; 1=Jan/Apr/Jul/Oct, 2=Feb/May/Aug/Nov, 3=Mar/Jun/Sep/Dec)',
        '  eom (int 1|0; when 1, uses last day of month for monthly/quarterly/annual and ignores day)',
        '  due_date (YYYY-MM-DD; used only when cadence=one_time)',
        '  start_date (YYYY-MM-DD; REQUIRED active window start; prevents overdue backfill)',
        '  end_date (YYYY-MM-DD; optional active window end)',
        '  remind_days (int; days before due date to show reminder)',
        '  is_active (int 1|0; archived when 0)',
        '',
        'Completion log entry fields (naming only; stored inside vms_due_log_v1):',
        '  ts (int; unix timestamp)',
        '  user_id (int; WP user)',
        '  obligation_id (string; foreign key → obligation.id)',
        '  due_date (YYYY-MM-DD)',
        '  notes (string)',
        '  proof_url (string)',
        '',
        'Engine file: vms/includes/core/due-dates.php',
        'Admin file: vms/includes/admin/due-dates.php',
      ),
    ),

	    'admissions' => array(
	      'title' => 'H) Guest List / Comp Admission',
	      'lines' => array(
	        'Storage: custom DB tables + wp_options/vms_settings',
        'Tables:',
        '{$wpdb->prefix}vms_admission_entries = “Guest list admissions rows (comp entries, status, check-in timestamps)”',
        '{$wpdb->prefix}vms_admission_audit = “Immutable admissions action log (entry_create/update/cancel/checkin/uncheckin/export_csv)”',
        '{$wpdb->prefix}vms_pass_sources = “Pass Claims source attribution records (people/business/partners)”',
        '{$wpdb->prefix}vms_pass_batches = “Pass Claims batch definitions (validity/value/check-in window settings)”',
        '{$wpdb->prefix}vms_pass_tokens = “Issued pass tokens (hashed token refs, claim status, claim linkage)”',
        '{$wpdb->prefix}vms_pass_claims = “Claim submissions (claimer fields + selected event + reservation linkage)”',
        'Capabilities:',
        'vms_admission_manage = “Manage/create/edit/cancel/export guest list entries”',
        'vms_door_checkin = “Use door check-in UI and check-in endpoints”',
	        'vms_admission_view_phone = “View unmasked phone values in door contexts”',
	      ),
	    ),

	    'staff_tasks' => array(
	      'title' => 'I) Staff Tasks System (Templates + Event Checklists)',
	      'lines' => array(
	        'Storage: custom DB tables + wp_options',
	        'Tables:',
	        '{$wpdb->prefix}vms_task_templates = “Reusable task template definitions (title, due rules, assignment rules)”',
	        '{$wpdb->prefix}vms_checklist_templates = “Checklist template definitions (default/by_venue/by_event_type)”',
	        '{$wpdb->prefix}vms_checklist_items = “Checklist-to-task links with optional per-item overrides JSON”',
	        '{$wpdb->prefix}vms_task_instances = “Event task instances with live status, due, assignment, and supersede linkage”',
	        '{$wpdb->prefix}vms_task_logs = “Immutable task action audit log”',
	        'Option keys:',
	        'vms_tasks_db_schema_version = “Staff Tasks DB schema version marker” (constant: VMS_OPT_TASKS_DB_SCHEMA_VERSION)',
	        'vms_tasks_settings_v1 = “Staff Tasks settings payload (horizon/regeneration/dashboard toggles)” (constant: VMS_OPT_TASKS_SETTINGS)',
	        'Cron hook:',
	        'vms_tasks_nightly_generator = “Nightly Staff Tasks generation hook name” (constant: VMS_CRON_TASKS_NIGHTLY)',
	        'Capabilities:',
	        'vms_manage_task_templates = “Manage task template definitions” (constant: VMS_CAP_TASKS_MANAGE_TEMPLATES)',
	        'vms_manage_checklist_templates = “Manage checklist template definitions” (constant: VMS_CAP_TASKS_MANAGE_CHECKLISTS)',
	        'vms_manage_tasks_all = “View and update all tasks across events” (constant: VMS_CAP_TASKS_MANAGE_ALL)',
	        'vms_complete_tasks_self = “Complete tasks assigned to the current user” (constant: VMS_CAP_TASKS_COMPLETE_SELF)',
	        'vms_view_tasks_self = “View only tasks assigned to the current user” (constant: VMS_CAP_TASKS_VIEW_SELF)',
	      ),
	    ),

	  );
	}
